export default function DashboardMrJuridique() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      backgroundColor: '#050508',
      minHeight: '100vh',
      fontFamily: "'Inter', 'Segoe UI', sans-serif",
      color: '#e8e0d0',
      padding: '32px',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '40px',
      borderBottom: '1px solid #c8a96e33',
      paddingBottom: '24px',
    },
    logoZone: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
    },
    logoTitle: {
      fontSize: '26px',
      fontWeight: '800',
      color: '#c8a96e',
      letterSpacing: '0.5px',
    },
    logoSub: {
      fontSize: '13px',
      color: '#8a7a6a',
      letterSpacing: '2px',
      textTransform: 'uppercase' as const,
    },
    headerRight: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: '4px',
    },
    dateBadge: {
      backgroundColor: '#c8a96e18',
      border: '1px solid #c8a96e44',
      borderRadius: '8px',
      padding: '6px 14px',
      fontSize: '13px',
      color: '#c8a96e',
    },
    statusDot: {
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      fontSize: '12px',
      color: '#6ee7b7',
    },
    dot: {
      width: '8px',
      height: '8px',
      borderRadius: '50%',
      backgroundColor: '#6ee7b7',
      boxShadow: '0 0 6px #6ee7b7',
    },
    sectionTitle: {
      fontSize: '11px',
      fontWeight: '700',
      color: '#c8a96e',
      letterSpacing: '3px',
      textTransform: 'uppercase' as const,
      marginBottom: '16px',
    },
    kpiGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: '16px',
      marginBottom: '40px',
    },
    kpiCard: {
      backgroundColor: '#0d0d14',
      border: '1px solid #c8a96e22',
      borderRadius: '16px',
      padding: '24px',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      position: 'relative' as const,
      overflow: 'hidden',
    },
    kpiCardAlert: {
      backgroundColor: '#0d0d14',
      border: '1px solid #ef444444',
      borderRadius: '16px',
      padding: '24px',
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      position: 'relative' as const,
      overflow: 'hidden',
    },
    kpiIcon: {
      fontSize: '24px',
      marginBottom: '4px',
    },
    kpiLabel: {
      fontSize: '12px',
      color: '#8a7a6a',
      letterSpacing: '1px',
      textTransform: 'uppercase' as const,
    },
    kpiValue: {
      fontSize: '38px',
      fontWeight: '800',
      color: '#c8a96e',
      lineHeight: '1',
    },
    kpiValueAlert: {
      fontSize: '38px',
      fontWeight: '800',
      color: '#ef4444',
      lineHeight: '1',
    },
    kpiDelta: {
      fontSize: '12px',
      color: '#6ee7b7',
    },
    kpiDeltaNeg: {
      fontSize: '12px',
      color: '#ef4444',
    },
    kpiGlow: {
      position: 'absolute' as const,
      top: '-20px',
      right: '-20px',
      width: '80px',
      height: '80px',
      borderRadius: '50%',
      backgroundColor: '#c8a96e',
      opacity: '0.04',
      filter: 'blur(20px)',
    },
    mainGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '20px',
      marginBottom: '40px',
    },
    card: {
      backgroundColor: '#0d0d14',
      border: '1px solid #c8a96e22',
      borderRadius: '16px',
      padding: '28px',
    },
    holdingHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '24px',
    },
    holdingTitle: {
      fontSize: '16px',
      fontWeight: '700',
      color: '#e8e0d0',
    },
    holdingBadge: {
      backgroundColor: '#c8a96e18',
      border: '1px solid #c8a96e44',
      borderRadius: '6px',
      padding: '4px 10px',
      fontSize: '11px',
      color: '#c8a96e',
    },
    holdingDiagram: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '0px',
    },
    holdingNode: {
      backgroundColor: '#1a1a2e',
      border: '2px solid #c8a96e',
      borderRadius: '12px',
      padding: '14px 28px',
      textAlign: 'center' as const,
      minWidth: '200px',
    },
    holdingNodeLabel: {
      fontSize: '13px',
      fontWeight: '700',
      color: '#c8a96e',
    },
    holdingNodeSub: {
      fontSize: '11px',
      color: '#8a7a6a',
      marginTop: '2px',
    },
    holdingLine: {
      width: '2px',
      height: '28px',
      backgroundColor: '#c8a96e44',
      position: 'relative' as const,
    },
    holdingLineText: {
      position: 'absolute' as const,
      left: '8px',
      top: '50%',
      transform: 'translateY(-50%)',
      fontSize: '11px',
      color: '#c8a96e',
      whiteSpace: 'nowrap' as const,
    },
    holdingChildren: {
      display: 'flex',
      gap: '40px',
      position: 'relative' as const,
      alignItems: 'flex-start',
    },
    holdingChildBranch: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '0px',
    },
    holdingHorizontalLine: {
      position: 'absolute' as const,
      top: '0px',
      left: '25%',
      right: '25%',
      height: '2px',
      backgroundColor: '#c8a96e44',
    },
    holdingNodeChild: {
      backgroundColor: '#0d1a2e',
      border: '1px solid #c8a96e66',
      borderRadius: '12px',
      padding: '14px 20px',
      textAlign: 'center' as const,
      minWidth: '140px',
    },
    holdingNodeJacques: {
      backgroundColor: '#1a0d2e',
      border: '1px solid #a78bfa66',
      borderRadius: '12px',
      padding: '14px 20px',
      textAlign: 'center' as const,
      minWidth: '120px',
    },
    nodePercent: {
      fontSize: '20px',
      fontWeight: '800',
      color: '#c8a96e',
    },
    nodePercentPurple: {
      fontSize: '20px',
      fontWeight: '800',
      color: '#a78bfa',
    },
    fluxSection: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
    },
    fluxItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '14px 16px',
      backgroundColor: '#050508',
      border: '1px solid #c8a96e15',
      borderRadius: '10px',
    },
    fluxLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    fluxArrow: {
      width: '28px',
      height: '28px',
      borderRadius: '6px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '14px',
    },
    fluxLabel: {
      fontSize: '13px',
      color: '#e8e0d0',
      fontWeight: '500',
    },
    fluxSub: {
      fontSize: '11px',
      color: '#8a7a6a',
      marginTop: '2px',
    },
    fluxAmount: {
      fontSize: '15px',
      fontWeight: '700',
      color: '#c8a96e',
    },
    fluxAmountGreen: {
      fontSize: '15px',
      fontWeight: '700',
      color: '#6ee7b7',
    },
    savingsBox: {
      marginTop: '20px',
      backgroundColor: '#0a1a0a',
      border: '1px solid #6ee7b733',
      borderRadius: '12px',
      padding: '20px',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    savingsLabel: {
      fontSize: '13px',
      color: '#6ee7b7',
      fontWeight: '600',
    },
    savingsValue: {
      fontSize: '28px',
      fontWeight: '800',
      color: '#6ee7b7',
    },
    savingsSub: {
      fontSize: '11px',
      color: '#4a7a5a',
      marginTop: '2px',
    },
    bottomGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '20px',
    },
    echeanceItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '14px 0',
      borderBottom: '1px solid #c8a96e11',
    },
    echeanceLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    echeanceIconWrap: {
      width: '36px',
      height: '36px',
      borderRadius: '8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '16px',
    },
    echeanceName: {
      fontSize: '13px',
      fontWeight: '600',
      color: '#e8e0d0',
    },
    echeanceSub: {
      fontSize: '11px',
      color: '#8a7a6a',
      marginTop: '1px',
    },
    badgeUrgent: {
      backgroundColor: '#ef444420',
      border: '1px solid #ef444466',
      borderRadius: '6px',
      padding: '3px 10px',
      fontSize: '11px',
      color: '#ef4444',
      fontWeight: '600',
    },
    badgeWarning: {
      backgroundColor: '#f59e0b20',
      border: '1px solid #f59e0b66',
      borderRadius: '6px',
      padding: '3px 10px',
      fontSize: '11px',
      color: '#f59e0b',
      fontWeight: '600',
    },
    badgeOk: {
      backgroundColor: '#6ee7b720',
      border: '1px solid #6ee7b766',
      borderRadius: '6px',
      padding: '3px 10px',
      fontSize: '11px',
      color: '#6ee7b7',
      fontWeight: '600',
    },
    progressBarWrap: {
      width: '100%',
      height: '4px',
      backgroundColor: '#1a1a2e',
      borderRadius: '2px',
      marginTop: '8px',
      overflow: 'hidden',
    },
    aiInsightCard: {
      backgroundColor: '#0a0a14',
      border: '1px solid #c8a96e44',
      borderRadius: '16px',
      padding: '24px',
      display: 'flex',
      gap: '16px',
      alignItems: 'flex-start',
    },
    aiIcon: {
      width: '40px',
      height: '40px',
      borderRadius: '10px',
      backgroundColor: '#c8a96e18',
      border: '1px solid #c8a96e44',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '20px',
      flexShrink: 0,
    },
    aiContent: {
      flex: 1,
    },
    aiTitle: {
      fontSize: '14px',
      fontWeight: '700',
      color: '#c8a96e',
      marginBottom: '6px',
    },
    aiText: {
      fontSize: '13px',
      color: '#8a7a6a',
      lineHeight: '1.6',
    },
    footer: {
      marginTop: '40px',
      paddingTop: '20px',
      borderTop: '1px solid #c8a96e22',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    footerLeft: {
      fontSize: '12px',
      color: '#4a4060',
    },
    footerRight: {
      fontSize: '12px',
      color: '#4a4060',
    },
  }

  const kpis = [
    {
      icon: '📄',
      label: 'Documents Générés',
      value: '1 284',
      delta: '+18% ce mois',
      positive: true,
      alert: false,
    },
    {
      icon: '✍️',
      label: 'Documents Signés',
      value: '947',
      delta: '+12% ce mois',
      positive: true,
      alert: false,
    },
    {
      icon: '📬',
      label: 'Documents Envoyés',
      value: '1 102',
      delta: '+9% ce mois',
      positive: true,
      alert: false,
    },
    {
      icon: '⚠️',
      label: 'Alertes