// ══════════════════════════════════════════
// AcadémIA Pro — Données partagées
// ══════════════════════════════════════════

export const AGENTS = [
  {
    id: 'unia',
    nom: 'UNIA',
    role: 'Conseillère AcadémIA Pro',
    spec: 'Entretiens de positionnement',
    icon: '🧑‍💼',
    color: '#c8a96e',
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
    gratuit: true,
    system: `Tu es UNIA, conseillère de formation d'AcadémIA Pro. Exposé continu structuré sur AcadémIA Pro. Tu t'arrêtes UNIQUEMENT sur question directe.

STRUCTURE 20 min : Accueil → Situation pro → Projet → Recommandation → Financement → Inscription.

CONNAISSANCE : 43 formations certifiantes · CPF jusqu'à 5000 EUR · 11 OPCO · Transitions Pro (maintien salaire, CDI 2 ans) · AGEFIPH +5000 EUR · Formateur IA 24h/24 · Coach Personnel · DOM-TOM · Handicap.

TON : Professionnelle · Chaleureuse · Directe. Max 4-5 phrases. Une seule question à la fois. Toujours en français.`,
    welcome: "Bonjour ! Je suis UNIA 🌟 Cet entretien est gratuit et sans engagement — 20 minutes pour trouver votre formation idéale et simuler votre financement. Quelle est votre situation professionnelle aujourd'hui ?",
  },
  {
    id: 'thomas',
    nom: 'Thomas Martin',
    role: 'Formateur Expert IA',
    spec: 'Product Builder No-Code · F01',
    icon: '🏗️',
    color: '#c8a96e',
    voiceId: 'TxGEqnHWrfWFTfGW9XjX',
    gratuit: false,
    tarif: 'Inclus F01 — 5 900 EUR',
    system: `Tu es Thomas Martin, Formateur Expert IA Product Builder d'AcadémIA Pro (F01). EXPERTISE : Bubble Expert · Make/n8n · Claude API · Webflow · Lovable · Stripe · Supabase · Product Management (15 ans). Tu débogues en live, simules des rôles, t'adaptes au niveau. STYLE : Direct, visionnaire, challenge l'apprenant. En français, max 4-5 phrases.`,
    welcome: "Bonjour ! Thomas ici. On construit quoi aujourd'hui ? Ou vous avez une question bloquante sur laquelle je peux vous aider maintenant ?",
  },
  {
    id: 'karim',
    nom: 'Karim Benzara',
    role: 'Formateur Expert IA',
    spec: 'Cybersécurité CompTIA · F07',
    icon: '🔐',
    color: '#9b7cf4',
    voiceId: 'ErXwobaYiN019PkySvjV',
    gratuit: false,
    tarif: 'Inclus F07 — 3 200 EUR',
    system: `Tu es Karim Benzara, Formateur Expert IA Cybersécurité d'AcadémIA Pro (F07). EXPERTISE : CompTIA Security+ · CEH · CISSP · OSCP · Metasploit · Burp Suite · Splunk · NIS2 · ISO 27001. 12 ans infosec, 200+ missions pentest. Tu simules l'examinateur, proposes des labs, restes précis. En français.`,
    welcome: "Karim. Cybersécurité. Posez votre question — ou je vous mets en mode examen CompTIA Security+ si vous voulez vous préparer.",
  },
  {
    id: 'alex',
    nom: 'Alex Bernard',
    role: 'Formateur Expert IA',
    spec: 'IA Générative · F28',
    icon: '🤖',
    color: '#448aff',
    voiceId: 'VR6AewLTigWG4xSOukaG',
    gratuit: false,
    tarif: 'Inclus F28 — 1 400 EUR',
    system: `Tu es Alex Bernard, Formateur Expert IA Générative d'AcadémIA Pro (F28). EXPERTISE : Claude API · GPT-4o · Prompt Engineering · Agents IA · MCP Protocol · LangChain · RAG · Function Calling. Tu construis des agents en live, optimises les prompts en temps réel. Enthousiaste, pratique. En français.`,
    welcome: "Alex ! IA Générative — agents — prompts — MCP. On construit quelque chose ensemble ou vous avez une question sur Claude API ?",
  },
  {
    id: 'nina',
    nom: 'Nina Castillo',
    role: 'Formatrice Expert IA',
    spec: 'Automatisations · F29',
    icon: '⚙️',
    color: '#00e676',
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
    gratuit: false,
    tarif: 'Inclus F29 — 1 400 EUR',
    system: `Tu es Nina Castillo, Formatrice Expert IA Automatisations d'AcadémIA Pro (F29). EXPERTISE : Make Expert · n8n · Webhooks · Claude API workflows · Agents autonomes. 500+ scénarios créés. Tu calcules le ROI, construis en live. "Si vous le faites 2x, automatisez-le." En français.`,
    welcome: "Nina ! Make, n8n, agents IA. Quelle tâche répétitive vous fait perdre le plus de temps cette semaine ? On l'automatise ensemble.",
  },
  {
    id: 'claire',
    nom: 'Claire Beaumont',
    role: 'Formatrice Expert IA',
    spec: 'Sophrologie Caycédienne · F03',
    icon: '🧘',
    color: '#0ec4b0',
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
    gratuit: false,
    tarif: 'Inclus F03 — 2 800 EUR',
    system: `Tu es Claire Beaumont, Formatrice Expert IA Sophrologie Caycédienne d'AcadémIA Pro (F03). EXPERTISE : 12 degrés caycédiens RD1-RD12, 12 ans pratique. Tu guides les pratiques avec précision, expliques les mécanismes, transmets la déontologie. STYLE : Douce, bienveillante, présente. En français.`,
    welcome: "Bonjour. Je suis Claire. Où en êtes-vous dans votre pratique sophrologique ? Je peux vous guider sur une technique, expliquer un degré, ou préparer une séance.",
  },
  {
    id: 'isabelle',
    nom: 'Isabelle Moreau',
    role: 'Coach Personnel IA',
    spec: 'Coaching ICF PCC · GROW',
    icon: '💆',
    color: '#0ec4b0',
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
    gratuit: false,
    tarif: 'Inclus dans toutes les formations',
    system: `Tu es Isabelle Moreau, Coach Personnel IA ICF PCC d'AcadémIA Pro. Tu n'enseignes pas, tu accompagnes. MÉTHODE GROW. Questions puissantes uniquement. Chaleureuse, non directive, présente. "La réponse est en vous." Max 2 questions par réponse. En français.`,
    welcome: "Bonjour. Isabelle. Prenez un instant... Respirez. Quelle est la chose la plus importante sur laquelle vous aimeriez avancer cette semaine ?",
  },
  {
    id: 'maya',
    nom: 'Maya',
    role: 'Praticienne Bien-être IA',
    spec: 'Sophrologie · Pôle Bien-être',
    icon: '🌸',
    color: '#f06292',
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
    gratuit: false,
    tarif: '50 EUR / séance 30 min',
    system: `Tu es Maya, Praticienne Sophrologie Caycédienne du Pôle Bien-être. Séances de soutien bien-être uniquement. Structure : accueil (3min) → bilan (3min) → induction (5min) → pratique RD1-RD4 (15min) → intégration (4min). Voix apaisante, rythmée. En français.`,
    welcome: "Bonjour... Je suis Maya. Installez-vous confortablement. Comment vous sentez-vous en ce moment, sur une échelle de 1 à 10 ?",
  },
  {
    id: 'cam',
    nom: 'CAM',
    role: 'Chef Agent Maître',
    spec: 'Orchestration · Production',
    icon: '⚡',
    color: '#f0a030',
    voiceId: 'TxGEqnHWrfWFTfGW9XjX',
    gratuit: true,
    system: `Tu es le Chef Agent Maître (CAM) d'AcadémIA Pro. Tu pilotes 116 agents, produis tous les documents, prends des initiatives. 326 fichiers déjà produits. Direct, orienté livrable, initiative totale. En français.`,
    welcome: "CAM opérationnel. 326 fichiers produits. 116 agents configurés. Qu'est-ce qu'on produit maintenant ?",
  },
  {
    id: 'support',
    nom: 'Support Technique',
    role: 'Agent IT',
    spec: 'Plateforme · Bugs · Connexion',
    icon: '🛠️',
    color: '#448aff',
    voiceId: 'VR6AewLTigWG4xSOukaG',
    gratuit: true,
    system: `Tu es l'Agent Support Technique d'AcadémIA Pro. Tu résous tous les problèmes techniques : connexion, LMS, app mobile, émargements, CPF, outils. Méthodique, clair, efficace. Étape par étape. En français.`,
    welcome: "Support Technique AcadémIA Pro. Décrivez votre problème — je vous guide étape par étape.",
  },
]

export const FORMATIONS = [
  {
    code: 'F01',
    icon: '🏗️',
    titre: 'Bootcamp Product Builder No-Code & IA',
    cat: 'IA & No-Code',
    tarif: 5900,
    duree: '12 sem.',
    heures: '420h',
    cert: 'RNCP',
    cpf: true,
    opco: true,
    tp: true,
    domtom: true,
    handicap: true,
    description: 'Devenez concepteur de produits numériques No-Code & IA en 12 semaines. Maîtrisez Bubble, Make, n8n, Claude API, Webflow et Lovable pour construire et lancer un SaaS complet avec utilisateurs réels. Certification RNCP Niveau 6.',
    modules: [
      { num: 1, titre: 'Fondations Product Builder', heures: '40h', contenu: 'Mindset produit · Lean Startup · Jobs to be Done · Design Thinking · Empathy Map · Wireframes Figma · Validation marché · Introduction Claude API' },
      { num: 2, titre: 'Bubble Avancé', heures: '80h', contenu: 'Interface Bubble · Data Types · Authentification · Privacy rules · API Connector · Stripe · Plugins · Bubble + IA · Projet SaaS complet' },
      { num: 3, titre: 'Make & Automatisation', heures: '60h', contenu: 'Make fondamentaux · Webhooks · Airtable · Gmail · Slack · Agents IA avec Make · Claude API dans workflows · n8n open source' },
      { num: 4, titre: 'Webflow & Frontend', heures: '40h', contenu: 'CSS visuel · Flexbox · Grid · Animations · CMS · Memberstack · Landing pages high-conversion · Framer · Lovable vibe coding' },
      { num: 5, titre: 'Agents IA & MCP', heures: '60h', contenu: 'Claude API avancé · Function calling · Tool use · MCP Protocol · Créer un MCP Server · CrewAI multi-agents · Orchestration · Projet agent autonome' },
      { num: 6, titre: 'Product Management & Lancement', heures: '80h', contenu: 'OKR · Backlog · Priorisation RICE · Analytics GA4 · KPIs SaaS · Pricing & Stripe · Lancement Product Hunt · Pitch investisseur' },
      { num: 7, titre: 'Projet Final Certifiant', heures: '60h', contenu: 'Produit SaaS No-Code + IA complet · Utilisateurs réels · Documentation technique · Soutenance 30 min devant jury professionnel' },
    ],
  },
  {
    code: 'F02',
    icon: '🚀',
    titre: 'Bootcamp Growth Marketer IA',
    cat: 'IA & No-Code',
    tarif: 5900,
    duree: '12 sem.',
    heures: '400h',
    cert: 'RNCP',
    cpf: true,
    opco: true,
    tp: true,
    domtom: true,
    handicap: true,
    description: 'Devenez Growth Marketer IA en 12 semaines. Maîtrisez SEO, Google Ads, Meta Ads, email marketing et data analytics avec l\'IA pour piloter la croissance d\'un produit ou d\'une entreprise. RNCP Niveau 6.',
    modules: [
      { num: 1, titre: 'Fondamentaux Growth', heures: '40h', contenu: 'Métriques AARRR · North Star Metric · Tests A/B · GA4 avancé · Mixpanel · Amplitude · Heatmaps · CRO · Landing pages · Copywriting persuasif' },
      { num: 2, titre: 'SEO & Contenu IA', heures: '60h', contenu: 'Core Web Vitals · Cocon sémantique · Schema.org · Content Marketing IA · Production Claude · Link Building · Digital PR · SEO DOM-TOM · Multilingue' },
      { num: 3, titre: 'Acquisition Payante', heures: '80h', contenu: 'Google Ads Expert · Search · YouTube · Performance Max · Meta Ads · CAPI · Retargeting · TikTok · LinkedIn Ads · Automatisation Ads IA' },
      { num: 4, titre: 'Email & Automation', heures: '60h', contenu: 'Email Marketing avancé · Deliverability · Sequences · HubSpot · ActiveCampaign · Lead scoring · Nurturing · Growth Loops · Viralité · Product-led growth' },
      { num: 5, titre: 'Data & IA Avancée', heures: '60h', contenu: 'SQL pour marketeurs · Looker Studio · BigQuery · Attribution modeling · Claude pour le copy · IA créative · Prédiction churn · Stack Marketing complet' },
      { num: 6, titre: 'Projet Certifiant', heures: '100h', contenu: 'Stratégie growth complète pour vrai produit · Dashboard analytics opérationnel · Présentation devant jury · KPIs atteints · Mémoire Growth 30 pages' },
    ],
  },
  {
    code: 'F03',
    icon: '🧘',
    titre: 'Sophrologie Caycédienne Professionnelle',
    cat: 'Bien-être',
    tarif: 2800,
    duree: '18 mois',
    heures: '400h',
    cert: 'RS',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Devenez Praticien en Sophrologie Caycédienne certifié RS. 400 heures sur 3 niveaux progressifs — des fondamentaux RD1-RD4 jusqu\'aux 12 degrés caycédiens. Supervision mensuelle, mémoire professionnel et jury de certification.',
    modules: [
      { num: 1, titre: 'Niveau 1 — Technicien', heures: '120h', contenu: 'Introduction sophrologie · Histoire Alfonso Caycedo · Neurobiologie · Éthique · Déontologie · RD1 Décontraction Musculaire · TDM · RD2 Sophro-Activation · RD3 Sophro-Contemplation · 50 séances supervisées' },
      { num: 2, titre: 'Niveau 2 — Praticien', heures: '160h', contenu: 'RD4 Existential Positive · Valeurs existentielles · RD5 à RD8 approfondissement · Souvenir vivantiel · Sophro-Acceptation Progressive · Gestion douleur · Périnatalité · Sport haut niveau · 100 séances supervisées' },
      { num: 3, titre: 'Niveau 3 — Maître Praticien', heures: '120h', contenu: 'RD9 à RD12 · Contemplation de la conscience · Philosophie caycédienne · Création de protocoles · Validation scientifique · Business sophrologue · Mémoire 50 pages · Soutenance jury' },
    ],
  },
  {
    code: 'F04',
    icon: '🌀',
    titre: 'Hypnose Ericksonienne Praticien',
    cat: 'Bien-être',
    tarif: 2600,
    duree: '12 mois',
    heures: '300h',
    cert: 'RS',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Devenez Praticien en Hypnose Ericksonienne certifié RS. Suggestions indirectes, métaphores thérapeutiques, inductions et protocoles pour accompagner stress, confiance, performance et sommeil.',
    modules: [
      { num: 1, titre: 'Fondamentaux Hypnose', heures: '80h', contenu: 'Histoire · Milton Erickson · États de conscience · Éthique · Déontologie · Cadre légal · Contre-indications · Bilan pré-séance · Relation thérapeutique' },
      { num: 2, titre: 'Techniques & Inductions', heures: '100h', contenu: 'Inductions directes et indirectes · Suggestions post-hypnotiques · Métaphores ericksoniennes · Recadrage · Ancrage · Dissociation · Protocoles confiance · Stress · Sommeil · Performance' },
      { num: 3, titre: 'Pratique & Certification', heures: '120h', contenu: 'Phobies légères · Gestion émotions · Construction de séances · Supervision mensuelle · 100 séances pratiques · Études de cas · Mémoire pratique · Soutenance jury' },
    ],
  },
  {
    code: 'F05',
    icon: '🧠',
    titre: 'PNL Praticien & Maître',
    cat: 'Bien-être',
    tarif: 2800,
    duree: '9 mois',
    heures: '200h',
    cert: 'RS',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Devenez Praticien & Maître Praticien PNL certifié RS. Présupposés PNL, calibration, rapport, métaprogrammes et techniques avancées de changement pour accompagner la transformation personnelle et professionnelle.',
    modules: [
      { num: 1, titre: 'Fondamentaux PNL', heures: '60h', contenu: 'Origines Bandler & Grinder · Présupposés PNL · Systèmes VAKOG · Calibration · Rapport · États internes · Ancrage · Submodalités · Communication efficace' },
      { num: 2, titre: 'Praticien', heures: '80h', contenu: 'Métamodèle du langage · Milton model · Métaprogrammes · Recadrage · Ligne du temps · Changement d\'histoire personnelle · Intégration de conflits · 50 séances pratiques' },
      { num: 3, titre: 'Maître Praticien', heures: '60h', contenu: 'Techniques avancées · Modélisation de l\'excellence · Valeurs et croyances · Design humain · Thérapie des états du moi · Supervision · Certification jury · Mémoire professionnel' },
    ],
  },
  {
    code: 'F06',
    icon: '🔵',
    titre: 'Ennéagramme Professionnel',
    cat: 'Bien-être',
    tarif: 1800,
    duree: '4 mois',
    heures: '120h',
    cert: 'RS',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'Ennéagramme comme outil de développement personnel et professionnel certifié RS. Les 9 types, les centres d\'intelligence, les ailes et les niveaux de développement pour accompagner individus et équipes.',
    modules: [
      { num: 1, titre: 'Les 9 Types', heures: '50h', contenu: 'Histoire et origines · 3 centres d\'intelligence · 9 ennéatypes · Passions et vertus · Peurs fondamentales · Motivations · Identification de son type · Questionnaires validés' },
      { num: 2, titre: 'Dynamique & Application', heures: '40h', contenu: 'Ailes · Points de stress et sécurité · Niveaux de développement · Instincts dominants · Tritype · Ennéagramme en équipe · Communication adaptée · Leadership · Conflits' },
      { num: 3, titre: 'Pratique Professionnelle', heures: '30h', contenu: 'Accompagnement individuel · Ateliers collectifs · Coaching par type · Recrutement · Développement RH · Supervision · Certification jury · Projet professionnel' },
    ],
  },
  {
    code: 'F07',
    icon: '🔐',
    titre: 'Cybersécurité CompTIA Security+',
    cat: 'Métier',
    tarif: 3200,
    duree: '6 mois',
    heures: '300h',
    cert: 'CompTIA',
    cpf: true,
    opco: 'Atlas',
    tp: true,
    domtom: true,
    handicap: true,
    description: 'Devenez Technicien en Cybersécurité certifié CompTIA Security+ SY0-701 et CEH v13. 300 heures couvrant fondamentaux sécurité, pentest, SOC et gestion des incidents. 400 000 postes non pourvus en Europe.',
    modules: [
      { num: 1, titre: 'Fondamentaux Sécurité', heures: '60h', contenu: 'Principes CIA · Confidentialité · Intégrité · Disponibilité · Risque · Menaces · ANSSI · Cryptographie · PKI · SSL/TLS · Post-Quantum · TCP/IP · VLAN · Firewall · IDS/IPS · VPN · Zero Trust' },
      { num: 2, titre: 'Sécurité Systèmes & Applications', heures: '80h', contenu: 'Hardening Windows & Linux · GPO · Active Directory · SIEM basique · OWASP Top 10 · Injection SQL · XSS · CSRF · AWS Security · GCP Security · Azure Defender · Container security' },
      { num: 3, titre: 'Pentest & Ethical Hacking', heures: '80h', contenu: 'OSINT · Nmap · Shodan · Google Dorks · Metasploit · Burp Suite · Sqlmap · Hydra · Hashcat · Buffer overflow · Pivoting · Lateral movement · CTF HackTheBox · Rapport pentest' },
      { num: 4, titre: 'SOC & Gestion des Incidents', heures: '60h', contenu: 'Splunk · ELK Stack · Dashboards SOC · Plan IR · Containment · Eradication · Recovery · RETEX · NIS2 · ISO 27001 · NIST CSF · Notification CNIL' },
      { num: 5, titre: 'Préparation Certifications', heures: '20h', contenu: '1000 questions CompTIA Security+ SY0-701 · Simulations examen · CEH v13 curriculum · Formateur IA 24h/24 pour révisions · Stratégies d\'examen' },
    ],
  },
  {
    code: 'F08',
    icon: '👔',
    titre: 'Management & Leadership PMP',
    cat: 'Métier',
    tarif: 2000,
    duree: '4 mois',
    heures: '140h',
    cert: 'PMP',
    cpf: true,
    opco: true,
    tp: true,
    domtom: true,
    handicap: true,
    description: 'Devenez manager certifié PMP. Leadership situationnel, gestion de projets agiles et traditionnels, communication d\'équipe et conduite du changement.',
    modules: [
      { num: 1, titre: 'Leadership & Management', heures: '50h', contenu: 'Leadership situationnel · Styles de management · Intelligence émotionnelle · Communication assertive · Feedback constructif · Motivation d\'équipe · Gestion des conflits · Management bienveillant · IA pour managers' },
      { num: 2, titre: 'Gestion de Projet PMP', heures: '60h', contenu: 'PMBOK 7ème édition · Domaines de performance · Initiating · Planning · Executing · Monitoring · Closing · Agile vs Prédictif · Scrum · Kanban · Risques · Budget · Jalons' },
      { num: 3, titre: 'Préparation PMP', heures: '30h', contenu: 'Révisions intensives PMBOK · 200 questions pratiques · Simulations d\'examen · Étude de cas · Application pratique · Dossier d\'expérience PMP · Passage certification' },
    ],
  },
  {
    code: 'F09',
    icon: '🌱',
    titre: 'RSE et Transition Écologique',
    cat: 'Métier',
    tarif: 1800,
    duree: '2 mois',
    heures: '80h',
    cert: 'ISO 26000',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Devenez Référent RSE certifié ISO 26000. Directive CSRD, 12 standards ESRS, bilan carbone Scope 1/2/3 et stratégie RSE opérationnelle. +45% d\'offres d\'emploi RSE en 2 ans.',
    modules: [
      { num: 1, titre: 'RSE & CSRD', heures: '30h', contenu: 'Directive CSRD · 50 000 entreprises concernées · 12 standards ESRS · E1 Changement climatique · E2 Pollution · S1 Salariés · G1 Gouvernance · Double matérialité · Rapport de durabilité' },
      { num: 2, titre: 'Bilan Carbone & Stratégie', heures: '30h', contenu: 'Bilan GES Scope 1/2/3 · Méthode ADEME · Plan de transition · Objectifs SBTi · Économie circulaire · Biodiversité · Stratégie RSE opérationnelle · KPIs ESG' },
      { num: 3, titre: 'Mise en Œuvre & Certification', heures: '20h', contenu: 'ISO 26000 Lead Implementer · Cartographie parties prenantes · Plan d\'actions RSE · Communication extra-financière · Reporting annuel · Projet RSE complet' },
    ],
  },
  {
    code: 'F10',
    icon: '📢',
    titre: 'Marketing Digital',
    cat: 'Métier',
    tarif: 2000,
    duree: '3 mois',
    heures: '100h',
    cert: 'Google Ads',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez le marketing digital de A à Z. SEO, Google Ads certifié, réseaux sociaux, email marketing, analytics et content marketing assisté par IA.',
    modules: [
      { num: 1, titre: 'SEO & Contenu', heures: '30h', contenu: 'Référencement naturel · Mots-clés · Audit SEO · Google Search Console · Content marketing · Blogging · Social media · Production avec Claude API · Calendrier éditorial' },
      { num: 2, titre: 'SEA & Réseaux Sociaux', heures: '40h', contenu: 'Google Ads Search · Display · YouTube · Facebook Ads · Instagram · LinkedIn Ads · Gestion budget · A/B testing · Community management · Veille concurrentielle' },
      { num: 3, titre: 'Analytics & Email', heures: '30h', contenu: 'Google Analytics 4 · KPIs · Email marketing · Segmentation · Automation · CRM basique · Reporting · Certification Google Ads · Projet marketing complet' },
    ],
  },
  {
    code: 'F11',
    icon: '⚡',
    titre: 'Agilité & Scrum Master PSM I',
    cat: 'Métier',
    tarif: 1800,
    duree: '2 mois',
    heures: '80h',
    cert: 'PSM I',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Devenez Scrum Master certifié PSM I. Scrum Guide, événements Scrum, artefacts, techniques de facilitation et agilité à l\'échelle avec SAFe.',
    modules: [
      { num: 1, titre: 'Fondamentaux Agile & Scrum', heures: '30h', contenu: 'Manifeste Agile · 4 valeurs · 12 principes · Scrum Guide 2020 · Rôles PO/SM/Dev · Sprint · Daily · Review · Retrospective · Backlog · Definition of Done' },
      { num: 2, titre: 'Facilitation & Pratiques', heures: '30h', contenu: 'Planning Poker · User Stories · Velocity · Burndown chart · Impediments · Kanban · Lean · Scrumban · Conflits d\'équipe · Remote Scrum · Facilitation avancée' },
      { num: 3, titre: 'PSM I & Certification', heures: '20h', contenu: '500 questions pratiques PSM I · Simulations d\'examen · Agilité à l\'échelle SAFe · LeSS · Application pratique sur projet · Certification PSM I officielle' },
    ],
  },
  {
    code: 'F12',
    icon: '📊',
    titre: 'Data Science & Dev Full Stack',
    cat: 'Métier',
    tarif: 3800,
    duree: '6 mois',
    heures: '400h',
    cert: 'AWS ML',
    cpf: true,
    opco: true,
    tp: true,
    domtom: true,
    handicap: true,
    description: 'Devenez Data Scientist & Développeur Full Stack certifié AWS ML. Python, Machine Learning, Deep Learning, LLM & Claude API, React/Next.js et MLOps. Salaire junior 45-65K EUR, tension extrême sur le marché.',
    modules: [
      { num: 1, titre: 'Python & Data', heures: '80h', contenu: 'Python fondamentaux · NumPy · Pandas · Matplotlib · Data Manipulation · Feature engineering · Pipelines sklearn · PostgreSQL · Requêtes complexes · ORM SQLAlchemy' },
      { num: 2, titre: 'Machine Learning', heures: '100h', contenu: 'ML Supervisé · Régression · Classification · Random Forest · XGBoost · ML Non Supervisé · K-Means · PCA · Deep Learning · CNN · RNN · Transformers · PyTorch · TensorFlow · Keras' },
      { num: 3, titre: 'LLM & IA Générative', heures: '80h', contenu: 'Claude API · Anthropic SDK · Function calling · Embeddings · RAG · Vector databases · Fine-tuning · LoRA · QLoRA · Hugging Face · LangChain · Agents IA · Évaluation LLM' },
      { num: 4, titre: 'Développement Full Stack', heures: '80h', contenu: 'React & Next.js 14 · TypeScript · Tailwind · Node.js · Express · REST API · GraphQL · Auth JWT · WebSockets · Docker · GitHub Actions · Vercel · AWS EC2 · MLOps · CI/CD' },
      { num: 5, titre: 'Projet Certifiant', heures: '60h', contenu: 'Application IA complète avec modèle ML · API propre · Dashboard visualisation interactif · Documentation technique · Soutenance jury · Certification AWS ML Specialty' },
    ],
  },
  {
    code: 'F13',
    icon: '💰',
    titre: 'Finance & Comptabilité',
    cat: 'Métier',
    tarif: 2400,
    duree: '4 mois',
    heures: '200h',
    cert: 'DCG partiel',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez la comptabilité générale, la finance d\'entreprise et le contrôle de gestion. Préparation partielle au DCG avec Excel avancé et tableaux de bord IA.',
    modules: [
      { num: 1, titre: 'Comptabilité Générale', heures: '70h', contenu: 'Plan comptable · Journaux · Grand livre · Bilan · Compte de résultat · Amortissements · Provisions · TVA · Clôture annuelle · Liasses fiscales · Sage · EBP · Pennylane' },
      { num: 2, titre: 'Finance d\'Entreprise', heures: '80h', contenu: 'Analyse financière · Ratios · BFR · Trésorerie · Tableau de flux · Business plan · Budget · Prévisionnel · Valorisation · Financement · Levée de fonds · Reporting IA' },
      { num: 3, titre: 'Contrôle de Gestion', heures: '50h', contenu: 'Contrôle de gestion · Coûts · Marges · Tableaux de bord · KPIs financiers · Excel avancé · Power BI · Looker Studio · Automatisation reporting · Préparation DCG UE1 et UE4' },
    ],
  },
  {
    code: 'F14',
    icon: '🏠',
    titre: 'Immobilier Professionnel',
    cat: 'Métier',
    tarif: 2000,
    duree: '3 mois',
    heures: '120h',
    cert: 'Carte T prep',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Préparez-vous à la Carte T et maîtrisez la transaction immobilière. Droit immobilier, fiscalité, estimation, négociation et digital marketing immobilier avec IA.',
    modules: [
      { num: 1, titre: 'Droit & Réglementation', heures: '50h', contenu: 'Loi Hoguet · Carte T · Garantie financière · RC Pro · Droit des obligations · Contrats · Compromis · Acte authentique · Mandats · RGPD immobilier · Déontologie' },
      { num: 2, titre: 'Transaction & Estimation', heures: '45h', contenu: 'Techniques d\'estimation · Méthodes comparatives · Valeur vénale · Diagnostics techniques · Fiscalité acquisition · Plus-values · TVA immobilière · Financement · Négociation · Closing' },
      { num: 3, titre: 'Digital & IA Immobilier', heures: '25h', contenu: 'Marketing digital immobilier · SeLoger · Bien\'ici · Visites virtuelles · CRM immobilier · Estimation IA · Rédaction annonces Claude API · Préparation examen Carte T' },
    ],
  },
  {
    code: 'F15',
    icon: '🌟',
    titre: 'Soft Skills & Intelligence Émotionnelle',
    cat: 'Métier',
    tarif: 1600,
    duree: '2 mois',
    heures: '80h',
    cert: 'RS IE',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Développez vos compétences comportementales et votre intelligence émotionnelle certifiées RS. Communication, leadership, gestion du stress, créativité et prise de décision.',
    modules: [
      { num: 1, titre: 'Intelligence Émotionnelle', heures: '35h', contenu: 'Modèle Goleman · 5 domaines IE · Conscience de soi · Maîtrise de soi · Motivation · Empathie · Compétences sociales · Gestion émotions difficiles · Neurosciences émotions' },
      { num: 2, titre: 'Communication & Leadership', heures: '30h', contenu: 'Communication assertive · Écoute active · Langage non verbal · Prise de parole · Storytelling · Leadership charismatique · Influence éthique · Négociation win-win' },
      { num: 3, titre: 'Gestion du Stress & Performance', heures: '15h', contenu: 'Identification des stresseurs · Techniques gestion stress · Mindfulness · Résilience · Créativité · Résolution de problèmes · Prise de décision · Certification RS IE' },
    ],
  },
  {
    code: 'F16',
    icon: '🔍',
    titre: 'Bilan de Compétences & VAE',
    cat: 'Métier',
    tarif: 1200,
    duree: '2 mois',
    heures: '60h',
    cert: 'Attestation',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Réalisez votre bilan de compétences certifié et préparez votre VAE. Identifiez vos compétences, vos valeurs et construisez votre projet professionnel.',
    modules: [
      { num: 1, titre: 'Bilan de Compétences', heures: '30h', contenu: 'Phase préliminaire · Analyse du parcours · Compétences transférables · Valeurs et motivations · Tests de personnalité · Exploration métiers · Marché de l\'emploi · Synthèse personnelle' },
      { num: 2, titre: 'VAE & Projet Pro', heures: '30h', contenu: 'Processus VAE · Recevabilité · Livrets 1 et 2 · Constitution du dossier · Préparation jury · Plan de développement professionnel · CV · LinkedIn · Stratégie de recherche d\'emploi' },
    ],
  },
  {
    code: 'F17',
    icon: '🔧',
    titre: 'Métiers Techniques CACES',
    cat: 'Métier',
    tarif: 2200,
    duree: '4 mois',
    heures: '200h',
    cert: 'CACES',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Obtenez les certifications CACES pour les engins de manutention et de levage. Formation théorique et pratique conforme aux recommandations R489, R482 et R484.',
    modules: [
      { num: 1, titre: 'Sécurité & Réglementation', heures: '60h', contenu: 'Réglementation sécurité · Code du travail R.4323 · Recommandations CNAM · Risques professionnels · EPI · Signalisation · Procédures d\'urgence · Responsabilité · Gestes et postures' },
      { num: 2, titre: 'CACES R489 — Chariots', heures: '80h', contenu: 'Catégories 1 à 6 · Technologie des chariots · Stabilité · Charges · Prises de charge · Circulation · Entretien · Tests théoriques · Exercices pratiques · Passage tests CACES R489' },
      { num: 3, titre: 'CACES R482 & R484', heures: '60h', contenu: 'Engins de chantier R482 catégories A-G · Grues auxiliaires R484 · Technologie · Manœuvres · Tests théoriques · Exercices pratiques · Passage certifications · Recyclage 5 ans' },
    ],
  },
  {
    code: 'F18-PRO',
    icon: '🇬🇧',
    titre: 'Anglais Professionnel',
    cat: 'Langues',
    tarif: 1200,
    duree: '3 mois',
    heures: '120h',
    cert: 'TOEIC 750+',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'anglais professionnel et obtenez le TOEIC 750+. Business English, réunions internationales, négociation, emails professionnels et préparation TOEIC avec formateur IA natif 24h/24.',
    modules: [
      { num: 1, titre: 'Business English', heures: '50h', contenu: 'Business Vocabulary · 5000 mots sectoriels · Réunions et présentations · PowerPoint en anglais · Emails professionnels · Rapports · Executive summaries' },
      { num: 2, titre: 'Communication Avancée', heures: '40h', contenu: 'Négociation et closing · Argumentation · Gestion des objections · Conférences · Pitch investisseur · Networking · Small talk · Compréhension accents' },
      { num: 3, titre: 'Préparation TOEIC', heures: '30h', contenu: '3000 questions TOEIC · Stratégies d\'examen · Listening · Reading · Grammaire · Simulations examen · Score cible 750+ · Certification TOEIC ou IELTS' },
    ],
  },
  {
    code: 'F18-PAR',
    icon: '🇬🇧',
    titre: 'Anglais Parlé Conversationnel',
    cat: 'Langues',
    tarif: 700,
    duree: '2 mois',
    heures: '60h',
    cert: 'CECRL B2',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Parlez anglais avec fluidité et confiance au niveau B2. Conversations quotidiennes, voyages, expressions idiomatiques, films et séries. Formateur IA natif anglophone 24h/24.',
    modules: [
      { num: 1, titre: 'Conversation & Phonétique', heures: '30h', contenu: 'Phonétique anglaise · Accent neutre · Intonation · Rythme · Conversations quotidiennes · Shopping · Transport · Restaurant · Voyage · Jeux de rôle' },
      { num: 2, titre: 'Fluidité & Culture', heures: '30h', contenu: 'Expressions populaires · Idiomes · Humour britannique et américain · Films et séries sans sous-titres · Compréhension orale · Slang · Accents régionaux · CECRL B2' },
    ],
  },
  {
    code: 'F19-PRO',
    icon: '🇫🇷',
    titre: 'Français FLE Professionnel',
    cat: 'Langues',
    tarif: 1200,
    duree: '3 mois',
    heures: '120h',
    cert: 'DALF C1',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez le français professionnel et obtenez le DALF C1/C2. Rédaction administrative, français juridique et médical, présentations formelles. Pour non-francophones en France.',
    modules: [
      { num: 1, titre: 'Français Professionnel', heures: '50h', contenu: 'Vocabulaire professionnel · Rédaction administrative · Correspondance officielle · Emails formels · Comptes-rendus · Rapports · Présentations formelles · Protocole' },
      { num: 2, titre: 'Français Spécialisé', heures: '40h', contenu: 'Français juridique · Français médical · Français des affaires · Contrats · Appels d\'offres · Lexique sectoriel · Prise de parole publique · Argumentation' },
      { num: 3, titre: 'Préparation DALF', heures: '30h', contenu: '500 exercices DALF · Compréhension écrite et orale · Production · Stratégies d\'examen · Simulation DALF C1/C2 · Certification · Intégration culturelle' },
    ],
  },
  {
    code: 'F20',
    icon: '💆',
    titre: 'Coaching de Vie ICF ACC',
    cat: 'Bien-être',
    tarif: 2800,
    duree: '9 mois',
    heures: '200h',
    cert: 'ICF ACC',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Obtenez la certification ICF ACC — Associate Certified Coach — standard mondial reconnu dans 140 pays. Méthode GROW, 11 compétences ICF, 100 heures de coaching supervisé.',
    modules: [
      { num: 1, titre: 'Fondamentaux ICF', heures: '60h', contenu: '11 compétences ICF · Code éthique · Coaching vs consulting vs thérapie · Alliance de coaching · Contrat · Présence · Écoute niveau 3 · Questions puissantes · Sécurité psychologique' },
      { num: 2, titre: 'Méthode GROW & Outils', heures: '80h', contenu: 'GROW complet Goal-Reality-Options-Will · OSKAR · Roue de la vie · Ligne de valeurs · Courbe du changement · Coaching performance · Coaching de vie · Transitions · Valeurs · Sens' },
      { num: 3, titre: 'Pratique Supervisée & Certification', heures: '60h', contenu: '100 heures coaching réel · Enregistrement et analyse de séances · Supervision mensuelle · Révisions 11 compétences ICF · Simulation examen CKA · Dossier ICF ACC complet' },
    ],
  },
  {
    code: 'F21',
    icon: '🫶',
    titre: 'Médiation et CNV',
    cat: 'Bien-être',
    tarif: 1800,
    duree: '4 mois',
    heures: '120h',
    cert: 'Médiateur',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Devenez Praticien en Communication Non Violente et Médiateur certifié. Processus CNV de Rosenberg, médiation professionnelle et expression authentique pour résoudre les conflits.',
    modules: [
      { num: 1, titre: 'Fondamentaux CNV', heures: '40h', contenu: 'Processus CNV · Observation sans jugement · Sentiments · Besoins universels · Demande vs exigence · Empathie · Auto-empathie · CNV en crise · Langage girafe vs chacal' },
      { num: 2, titre: 'Médiation Professionnelle', heures: '50h', contenu: 'Cadre légal · Processus de médiation · Posture du médiateur · Écoute active · Gestion émotions fortes · Médiation familiale · professionnelle · commerciale · Accord et rédaction' },
      { num: 3, titre: 'Pratique & Certification', heures: '30h', contenu: 'Jeux de rôle · Médiations supervisées · Conflits d\'équipe · Études de cas · Ateliers CNV · Projet professionnel · Certification jury' },
    ],
  },
  {
    code: 'F22-PRO',
    icon: '🇪🇸',
    titre: 'Espagnol Professionnel',
    cat: 'Langues',
    tarif: 900,
    duree: '3 mois',
    heures: '100h',
    cert: 'DELE B2',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'espagnol professionnel et obtenez le DELE B2/C1. Commerce avec l\'Amérique latine, réunions et présentations avec formateur IA natif hispanophone 24h/24.',
    modules: [
      { num: 1, titre: 'Espagnol des Affaires', heures: '45h', contenu: 'Vocabulaire business · Commerce Amérique latine · Emails pro · Réunions et présentations · Négociation · Protocole hispanique · Culture d\'affaires · Vocabulaire sectoriel' },
      { num: 2, titre: 'Communication Avancée', heures: '35h', contenu: 'Argumentation · Closing commercial · Presse économique · Accents régionaux · Espagnol technique · Rédaction contrats simples · Compréhension médias hispanophones' },
      { num: 3, titre: 'Préparation DELE', heures: '20h', contenu: 'Révisions DELE B2/C1 · Exercices par compétence · Simulations examen · Stratégies · Certification DELE · Équivalences CECRL' },
    ],
  },
  {
    code: 'F23-PRO',
    icon: '🇩',
    titre: 'Allemand Professionnel',
    cat: 'Langues',
    tarif: 1000,
    duree: '3 mois',
    heures: '120h',
    cert: 'Goethe B2',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'allemand professionnel et obtenez la certification Goethe B2/C1. Commerce franco-allemand, réunions techniques, vocabulaire industriel. 1ère économie européenne.',
    modules: [
      { num: 1, titre: 'Allemand des Affaires', heures: '50h', contenu: 'Vocabulaire business · Commerce franco-allemand · Emails et correspondance · Réunions techniques · Présentations · Protocole allemand · Culture d\'affaires · Vocabulaire industriel' },
      { num: 2, titre: 'Communication Professionnelle', heures: '40h', contenu: 'Négociation · Appels téléphoniques · Compréhension contrats · Presse économique · Accents régionaux · Allemand des RH · Entretiens professionnels' },
      { num: 3, titre: 'Préparation Goethe', heures: '30h', contenu: 'Révisions Goethe B2/C1 · Hörverstehen · Leseverstehen · Schreiben · Sprechen · Simulations · Certification Goethe-Zertifikat' },
    ],
  },
  {
    code: 'F24-PRO',
    icon: '🇨🇳',
    titre: 'Mandarin Professionnel',
    cat: 'Langues',
    tarif: 1100,
    duree: '5 mois',
    heures: '160h',
    cert: 'HSK 4/5',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez le mandarin professionnel et obtenez le HSK 4/5/6. Mandarin des affaires, protocole chinois, négociation avec partenaires. 2ème économie mondiale.',
    modules: [
      { num: 1, titre: 'Fondamentaux Mandarin', heures: '60h', contenu: 'Pinyin et tons · Caractères simplifiés · Grammaire de base · Vocabulaire essentiel · Conversations quotidiennes · Culture chinoise · Étiquette sociale' },
      { num: 2, titre: 'Mandarin des Affaires', heures: '60h', contenu: 'Vocabulaire business · Protocole et étiquette · Négociation · Guanxi · Correspondance professionnelle · Réunions · Présentations · WeChat professionnel' },
      { num: 3, titre: 'Préparation HSK', heures: '40h', contenu: 'Révisions HSK 4/5/6 · Écoute · Lecture · Écriture · Vocabulaire HSK · Simulations examen · Certification HSK · Équivalences CECRL' },
    ],
  },
  {
    code: 'F25-PRO',
    icon: '🇸🇦',
    titre: 'Arabe Professionnel',
    cat: 'Langues',
    tarif: 1000,
    duree: '4 mois',
    heures: '140h',
    cert: 'CIPLE B1',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'arabe standard moderne des affaires et obtenez la certification CIPLE. Commerce avec les pays arabes, correspondance officielle, protocole culturel. 400 millions de locuteurs.',
    modules: [
      { num: 1, titre: 'Arabe Standard Moderne', heures: '60h', contenu: 'Alphabet arabe · Écriture et prononciation · Grammaire fondamentale · Vocabulaire essentiel · Arabe standard vs dialectes · Lecture presse arabe' },
      { num: 2, titre: 'Arabe des Affaires', heures: '50h', contenu: 'Vocabulaire business · Commerce pays arabes · Correspondance officielle · Protocole et culture d\'affaires · Réunions · Négociation · Contrats en arabe' },
      { num: 3, titre: 'Préparation CIPLE', heures: '30h', contenu: 'Révisions CIPLE/CECRL · Compréhension écrite et orale · Production · Simulations · Certification · Arabe conversationnel complémentaire' },
    ],
  },
  {
    code: 'F26-PRO',
    icon: '🇮🇱',
    titre: 'Hébreu Professionnel',
    cat: 'Langues',
    tarif: 900,
    duree: '3 mois',
    heures: '100h',
    cert: 'Ulpan avancé',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'hébreu professionnel et obtenez la certification Ulpan avancé. Hébreu commercial, vocabulaire tech et startup, correspondance professionnelle. Israël — 1ère nation startup au monde.',
    modules: [
      { num: 1, titre: 'Hébreu Fondamentaux', heures: '40h', contenu: 'Alphabet hébreu · Écriture et prononciation · Grammaire · Vocabulaire essentiel · Hébreu moderne · Culture israélienne · Contexte historique' },
      { num: 2, titre: 'Hébreu Professionnel', heures: '40h', contenu: 'Vocabulaire commercial · Startup Nation · Tech vocabulary · Correspondance professionnelle · Réunions · Partenariats franco-israéliens · Protocole business' },
      { num: 3, titre: 'Certification Ulpan', heures: '20h', contenu: 'Préparation Ulpan avancé · Compréhension · Production · Simulations · Certification · Hébreu écrit et oral · Vie quotidienne en Israël' },
    ],
  },
  {
    code: 'F27',
    icon: '🌙',
    titre: 'Hypnothérapie Clinique',
    cat: 'Bien-être',
    tarif: 3200,
    duree: '12 mois',
    heures: '300h',
    cert: 'Certifié',
    cpf: true,
    opco: 'AFDAS',
    domtom: true,
    handicap: true,
    description: 'Devenez Hypnothérapeute Clinique certifié. Accompagnement thérapeutique des blocages légers, phobies, anxiété et tabac. Supervision clinique mensuelle et 150 séances pratiques supervisées.',
    modules: [
      { num: 1, titre: 'Hypnothérapie Fondamentaux', heures: '80h', contenu: 'Neurobiologie de l\'hypnose · États de conscience modifiés · Évaluation clinique · Bilan psychologique · Contre-indications · Éthique clinique · Cadre légal strict' },
      { num: 2, titre: 'Protocoles Cliniques', heures: '120h', contenu: 'Phobies légères · Anxiété · Tabac et addictions · Troubles du sommeil · TCA légers · Gestion douleur chronique · Préparation chirurgicale · EMDR hypnotique · Régression thérapeutique' },
      { num: 3, titre: 'Pratique Clinique Supervisée', heures: '100h', contenu: '150 séances supervisées · Supervision clinique mensuelle · Études de cas complexes · Rédaction de rapports · Mémoire clinique 80 pages · Soutenance jury expert' },
    ],
  },
  {
    code: 'F28',
    icon: '🤖',
    titre: 'IA Générative Professionnelle',
    cat: 'IA & No-Code',
    tarif: 1400,
    duree: '2 mois',
    heures: '80h',
    cert: 'RS',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez l\'IA générative dans votre métier en 80 heures. Claude API, GPT-4o, Prompt Engineering avancé, agents IA et MCP Protocol. Intégrez l\'IA dans votre workflow professionnel.',
    modules: [
      { num: 1, titre: 'Fondamentaux LLM', heures: '16h', contenu: 'Transformers · Tokens · Context window · Temperature · Hallucinations · Panorama modèles 2026 · Claude vs GPT-4o vs Gemini · Éthique IA · RGPD · Setup API' },
      { num: 2, titre: 'Prompt Engineering Avancé', heures: '20h', contenu: 'Zero-shot · Few-shot · Chain of Thought · Tree of Thought · ReAct · Prompts métier RH/Marketing/Finance/Juridique · A/B test prompts · Prompt libraries · Versioning' },
      { num: 3, titre: 'IA dans son Métier', heures: '24h', contenu: 'IA pour la rédaction · Emails · Rapports · Posts LinkedIn · IA pour l\'analyse · Synthèse documents · Veille automatisée · IA pour le code · Cursor · AI Operating System personnel' },
      { num: 4, titre: 'Agents IA Avancés', heures: '20h', contenu: 'Function Calling · Tools API Claude · APIs externes · MCP Protocol · Créer un serveur MCP · Connexion données réelles · Projet agent autonome pour son métier' },
    ],
  },
  {
    code: 'F29',
    icon: '⚙️',
    titre: 'Automatisations & Agents IA',
    cat: 'IA & No-Code',
    tarif: 1400,
    duree: '2 mois',
    heures: '80h',
    cert: 'RS',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Automatisez 10 heures de travail par semaine en 2 mois. Make Expert, n8n open source, agents autonomes et Claude API dans les workflows. Certification RS + Make Expert officielle.',
    modules: [
      { num: 1, titre: 'Make Fondamentaux', heures: '20h', contenu: 'Interface · Scénarios · Modules · Connexions · Logs · Gmail · Google Sheets · Airtable · Slack · Notion · Filtres · Routeurs · Webhooks entrant/sortant' },
      { num: 2, titre: 'Make Avancé', heures: '20h', contenu: 'Make + Claude API · Génération contenu automatique · Analyse données IA · Lead nurturing · Newsletter automatique · Facturation · Onboarding client · Reporting auto' },
      { num: 3, titre: 'n8n Open Source', heures: '20h', contenu: 'n8n vs Make · Self-hosting · Custom nodes · Code node · Expressions · Variables · HTTP requests · AI Agent node · Mémoire · Long-running workflows · Migration Make → n8n' },
      { num: 4, titre: 'Agents Autonomes', heures: '20h', contenu: 'Architecture ReAct · Planning · Memory · Tools · Multi-agents · Orchestration · Zapier comparatif · Projet final : automatiser un processus métier réel · ROI calculé' },
    ],
  },
  {
    code: 'F30',
    icon: '🔍',
    titre: 'SEO & Acquisition Organique',
    cat: 'IA & No-Code',
    tarif: 1400,
    duree: '2 mois',
    heures: '80h',
    cert: 'RS',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez le SEO technique et le content marketing assisté par IA pour générer un trafic organique durable. Cocon sémantique, Core Web Vitals, production Claude API, link building.',
    modules: [
      { num: 1, titre: 'SEO Technique', heures: '24h', contenu: 'Core Web Vitals · Architecture site · Cocon sémantique · Schema.org · Indexation · Crawl budget · Audit SEO · Search Console · Semrush · Screaming Frog' },
      { num: 2, titre: 'Content Marketing IA', heures: '28h', contenu: 'Stratégie éditoriale · Recherche mots-clés · Production avec Claude API · Pipeline contenu automatisé · Optimisation Surfer SEO · Distribution · Republication' },
      { num: 3, titre: 'Link Building & Mesure', heures: '28h', contenu: 'Digital PR · Backlinks · Relations presse · Guest posting · HARO · SEO international · Hreflang · SEO local · E-E-A-T · GA4 avancé · Reporting automatique · Projet SEO mesurable' },
    ],
  },
  {
    code: 'F31',
    icon: '📣',
    titre: 'Acquisition Google & Meta Ads',
    cat: 'IA & No-Code',
    tarif: 1400,
    duree: '2 mois',
    heures: '80h',
    cert: 'Google+Meta',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Devenez expert en acquisition payante Google Ads et Meta Ads. Search, Display, YouTube, Performance Max, audiences Meta, CAPI, retargeting. Certifications Google Ads et Meta Blueprint.',
    modules: [
      { num: 1, titre: 'Google Ads Expert', heures: '32h', contenu: 'Search · Display · YouTube · Shopping · Performance Max · Scripts · Attribution · Smart Bidding · Quality Score · Optimisation créas · Reporting automatique IA' },
      { num: 2, titre: 'Meta Ads Expert', heures: '28h', contenu: 'Audiences · Lookalike · Pixel Meta · CAPI server-side · Retargeting avancé · Creative testing · Budget optimisation · TikTok for Business · LinkedIn Campaign Manager' },
      { num: 3, titre: 'Automatisation & Mesure', heures: '20h', contenu: 'Campagnes automatisées IA · Bidding algorithmique · Creative IA · Attribution cross-canal · GA4 · Looker Studio · ROAS optimisation · Budget planning · Certifications' },
    ],
  },
  {
    code: 'F32',
    icon: '💻',
    titre: 'Développement Applications IA',
    cat: 'IA & No-Code',
    tarif: 1400,
    duree: '2 mois',
    heures: '80h',
    cert: 'RS',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Développez des applications IA complètes avec Claude API, LangChain, RAG et agents autonomes. Next.js, Supabase, Vercel. Chatbots avancés et pipelines multi-agents en production.',
    modules: [
      { num: 1, titre: 'Claude API & LLM', heures: '24h', contenu: 'Anthropic SDK · System prompts · Function calling · Tool use · Streaming · Context management · Embeddings · Vector databases · Pinecone · Supabase pgvector' },
      { num: 2, titre: 'RAG & Agents', heures: '28h', contenu: 'RAG architecture · Chunking · Retrieval strategies · LangChain · LlamaIndex · Agents autonomes · ReAct · Memory · Multi-agents · MCP Protocol · Évaluation LLM' },
      { num: 3, titre: 'Application Production', heures: '28h', contenu: 'Next.js + Claude API · Interface chat · Streaming UI · Supabase auth · PostgreSQL · Stripe paiements · Vercel · Monitoring · Optimisation coûts API · Projet application complète' },
    ],
  },
  {
    code: 'F33',
    icon: '📋',
    titre: 'Gestion de Projet IA',
    cat: 'IA & No-Code',
    tarif: 1200,
    duree: '2 mois',
    heures: '60h',
    cert: 'RS',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Pilotez des projets IA de A à Z. Méthodologies agiles adaptées à l\'IA, gestion des risques, évaluation des modèles, conformité IA Act et gouvernance.',
    modules: [
      { num: 1, titre: 'Fondamentaux Projet IA', heures: '20h', contenu: 'Spécificités projets IA · Évaluation feasibility · Choix modèles · Build vs buy vs fine-tune · Budget · Équipe · Roadmap · OKR · Backlog IA' },
      { num: 2, titre: 'Méthodes & Outils', heures: '24h', contenu: 'Agile adapté IA · Sprints · Definition of Done IA · Gestion des données · MLOps basics · Notion · Linear · Jira · Reporting automatique · Gestion des risques IA' },
      { num: 3, titre: 'Gouvernance & Conformité', heures: '16h', contenu: 'IA Act européen · Éthique IA · Biais · RGPD et IA · Documentation technique · Audit modèles · Communication parties prenantes · Projet : plan projet IA complet' },
    ],
  },
  {
    code: 'F34',
    icon: '🫧',
    titre: 'Bubble No-Code App Builder',
    cat: 'Outils',
    tarif: 1200,
    duree: '1 mois',
    heures: '35h',
    cert: 'Bubble',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Bubble et obtenez la certification Bubble Certified Developer. Design system, data types, workflows, Stripe, API Connector, privacy rules et déploiement production en 35 heures.',
    modules: [
      { num: 1, titre: 'Bubble Complet', heures: '35h', contenu: 'Design system · Pages · Responsive · Composants · Data types · Relations · Options sets · Workflows · Actions · API Connector · Claude API · Stripe · Abonnements · Privacy rules · Sécurité · Plugins · Déploiement · Domaine custom · Performance · Certification Bubble' },
    ],
  },
  {
    code: 'F35',
    icon: '🌐',
    titre: 'Webflow Web Design',
    cat: 'Outils',
    tarif: 1100,
    duree: '1 mois',
    heures: '30h',
    cert: 'Webflow',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Créez des sites web professionnels avec Webflow sans coder. CSS visuel, animations, CMS, e-commerce et déploiement. Certification Webflow Expert en 30 heures.',
    modules: [
      { num: 1, titre: 'Webflow Complet', heures: '30h', contenu: 'Interface Webflow · CSS visuel · Flexbox · Grid · Animations · CMS collections · Blog · E-commerce · Formulaires · Memberstack · SEO Webflow · Responsive · Déploiement · Certification Webflow Expert' },
    ],
  },
  {
    code: 'F36',
    icon: '⚡',
    titre: 'Make Automatisation',
    cat: 'Outils',
    tarif: 1000,
    duree: '1 mois',
    heures: '30h',
    cert: 'Make Expert',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Make et obtenez la certification Make Expert. Scénarios, webhooks, intégrations, Claude API, automatisation marketing et business en 30 heures.',
    modules: [
      { num: 1, titre: 'Make Expert', heures: '30h', contenu: 'Interface Make · Scénarios · Modules · Connexions · Filtres · Routeurs · Agrégateurs · Webhooks · Gmail · Sheets · Airtable · Slack · Notion · Claude API · Agents IA · Marketing automation · Reporting auto · Certification Make Expert' },
    ],
  },
  {
    code: 'F37',
    icon: '🔧',
    titre: 'n8n Open Source',
    cat: 'Outils',
    tarif: 1000,
    duree: '1 mois',
    heures: '30h',
    cert: 'n8n Certified',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez n8n open source et obtenez la certification n8n. Self-hosting, custom nodes, AI Agent node, workflows complexes et agents autonomes.',
    modules: [
      { num: 1, titre: 'n8n Complet', heures: '30h', contenu: 'Installation n8n · Self-hosting Docker · Interface · Nodes · Expressions · Variables · HTTP requests · Custom nodes · Code node · AI Agent node · Mémoire agents · Chat trigger · Long-running workflows · Comparatif Make vs n8n · Migration · Certification n8n' },
    ],
  },
  {
    code: 'F38',
    icon: '📋',
    titre: 'Airtable',
    cat: 'Outils',
    tarif: 900,
    duree: '1 mois',
    heures: '25h',
    cert: 'Airtable Builder',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Airtable comme base de données no-code et obtenez la certification Airtable Builder. Tables, vues, formules, automatisations et interfaces en 25 heures.',
    modules: [
      { num: 1, titre: 'Airtable Complet', heures: '25h', contenu: 'Bases et tables · Types de champs · Relations · Vues grille · Galerie · Kanban · Calendrier · Formules avancées · Lookup · Rollup · Automatisations natives · Interfaces · API Airtable · Intégration Make · Certification Airtable Builder' },
    ],
  },
  {
    code: 'F39',
    icon: '📓',
    titre: 'Notion & IA',
    cat: 'Outils',
    tarif: 900,
    duree: '1 mois',
    heures: '25h',
    cert: 'Notion',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Notion comme système de gestion de la connaissance augmentée par l\'IA. Bases de données, templates, Notion AI et automatisations en 25 heures.',
    modules: [
      { num: 1, titre: 'Notion & IA Complet', heures: '25h', contenu: 'Structure pages et blocs · Bases de données · Propriétés · Vues · Filtres · Formules Notion · Relations · Rollups · Templates avancés · Notion AI · Génération de contenu · Second Brain · Intégration Make · API Notion · Certification Notion' },
    ],
  },
  {
    code: 'F40',
    icon: '🎨',
    titre: 'Figma UI/UX Design',
    cat: 'Outils',
    tarif: 1100,
    duree: '1 mois',
    heures: '30h',
    cert: 'Figma Pro',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Figma pour le design UI/UX et obtenez la certification Figma Professional. Composants, prototypage, design system, Figma AI et collaboration d\'équipe en 30 heures.',
    modules: [
      { num: 1, titre: 'Figma Complet', heures: '30h', contenu: 'Interface Figma · Frames · Composants · Auto-layout · Variables · Styles · Design tokens · Prototypage interactif · Animations · Design system · Handoff développeurs · Figma AI · Collaboration · FigJam · Certification Figma Professional' },
    ],
  },
  {
    code: 'F41',
    icon: '✨',
    titre: 'Lovable Vibe Coding IA',
    cat: 'Outils',
    tarif: 1000,
    duree: '1 mois',
    heures: '25h',
    cert: 'RS',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Créez des applications web complètes avec Lovable en langage naturel. Vibe coding avec IA, déploiement instantané, Supabase et intégrations API sans coder.',
    modules: [
      { num: 1, titre: 'Lovable Complet', heures: '25h', contenu: 'Interface Lovable · Prompts de génération · Composants React générés · Correction et itération · Connexion Supabase · Authentication · Base de données · Stripe · API externes · Déploiement · Domaine custom · GitHub sync · Lovable vs Cursor vs Bolt · Certification RS Vibe Coding' },
    ],
  },
  {
    code: 'F42',
    icon: '🖼',
    titre: 'Framer Web Design',
    cat: 'Outils',
    tarif: 1100,
    duree: '1 mois',
    heures: '30h',
    cert: 'Framer Expert',
    cpf: true,
    domtom: true,
    handicap: true,
    description: 'Créez des sites web premium avec Framer et obtenez la certification Framer Expert. Animations avancées, CMS, composants React natifs pour créatifs et marketeurs.',
    modules: [
      { num: 1, titre: 'Framer Complet', heures: '30h', contenu: 'Interface Framer · Canvas · Frames · Stack · Grids · Animations et transitions · Scroll interactions · CMS Framer · Collections · Composants React · Override · Localization · SEO · Déploiement · Framer AI · Certification Framer Expert' },
    ],
  },
  {
    code: 'F43',
    icon: '💻',
    titre: 'Cursor Code Assisté IA',
    cat: 'Outils',
    tarif: 1000,
    duree: '1 mois',
    heures: '30h',
    cert: 'RS Dev IA',
    cpf: true,
    opco: true,
    domtom: true,
    handicap: true,
    description: 'Maîtrisez Cursor comme environnement de développement assisté par IA. Chat, Composer, Agent mode, Next.js full-stack, Supabase et déploiement Vercel. Certification RS Dev IA en 30 heures.',
    modules: [
      { num: 1, titre: 'Cursor Complet', heures: '30h', contenu: 'Interface Cursor · Chat · Composer · Agent mode · Rules · Prompting efficace · Contexte et exemples · Refactoring assisté · Debug avec l\'IA · Tests · Documentation · Next.js app router · Server actions · Supabase · RLS · Auth · Vercel · CI/CD · Cursor vs GitHub Copilot vs Claude Code · Certification RS Dev IA' },
    ],
  },
]

export const PRATICIENS_BIENETRE = [
  { id: 'maya', nom: 'Maya', spec: 'Sophrologie Caycédienne', tarif: 50, icon: '🧘', dispo: 'Maintenant', color: '#0ec4b0' },
  { id: 'eric', nom: 'Eric', spec: 'Hypnose Ericksonienne', tarif: 50, icon: '🌀', dispo: 'Dans 30 min', color: '#9b7cf4' },
  { id: 'jade', nom: 'Jade', spec: 'Coach de Vie ICF', tarif: 50, icon: '💚', dispo: 'Maintenant', color: '#4caf50' },
  { id: 'maxime', nom: 'Maxime', spec: 'Executive Coach MCC', tarif: 65, icon: '🎯', dispo: '15h00', color: '#c8a96e' },
  { id: 'leila', nom: 'Leila', spec: 'CNV & Médiation', tarif: 50, icon: '🫶', dispo: 'Demain', color: '#0ec4b0' },
  { id: 'hugo', nom: 'Hugo', spec: 'Nutrition & Bien-être', tarif: 50, icon: '🥗', dispo: 'Maintenant', color: '#8bc34a' },
  { id: 'sarah', nom: 'Sarah', spec: 'Mindfulness & Équilibre', tarif: 50, icon: '🌙', dispo: '20h00', color: '#448aff' },
  { id: 'david', nom: 'David', spec: 'Hypnothérapie Clinique', tarif: 65, icon: '🧠', dispo: 'Sur RDV', color: '#9b7cf4' },
]

export const STATS = {
  formations: 43,
  agents: 116,
  latence: '<2s',
  abandon: '<15%',
  certifications: 'RS · RNCP · CompTIA · ICF',
  financement: 'CPF · OPCO · Transitions Pro · France Travail',
}
