export default function PageAvenantPrevente() {
  const html = "<p style='background:rgba(200,169,110,0.1);border:1px solid rgba(200,169,110,0.3);border-radius:8px;padding:10px 16px;color:#c8a96e;font-size:12px;text-align:center;margin-bottom:24px;'>Le pr&eacute;sent avenant compl&egrave;te les CGVU d&rsquo;Acad&eacute;mIA Pro et pr&eacute;vaut sur elles pour les points qu&rsquo;il traite.</p><h1>AVENANT &mdash; CONDITIONS SP&Eacute;CIALES PR&Eacute;VENTE</h1>\n<hr />\n<p><strong>Soci&eacute;t&eacute; :</strong> Acad&eacute;mIA Pro LLC &mdash; 30 N Gould St STE R, Sheridan, WY 82801, &Eacute;tats-Unis. Contact : contact@academiapro.fr.</p>\n<p><em>Le pr&eacute;sent avenant s&rsquo;applique exclusivement aux Formations identifi&eacute;es comme &laquo; en pr&eacute;vente &raquo;. Pour les autres ventes, le mod&egrave;le de paiement int&eacute;gral des CGVU s&rsquo;applique.</em></p>\n<hr />\n<h2>ARTICLE 1 &mdash; CONDITION SUSPENSIVE</h2>\n<p>L&rsquo;inscription en pr&eacute;vente est soumise &agrave; l&rsquo;atteinte d&rsquo;un seuil minimum de <strong>trois (3) participants confirm&eacute;s</strong> dans un d&eacute;lai de trente (30) jours calendaires. Si le seuil n&rsquo;est pas atteint, le contrat est r&eacute;put&eacute; nul et l&rsquo;acompte int&eacute;gralement rembours&eacute; sous quatorze (14) jours.</p>\n<hr />\n<h2>ARTICLE 2 &mdash; ACOMPTE</h2>\n<p>Les sommes vers&eacute;es constituent un <strong>acompte</strong> (non des arrhes au sens de l&rsquo;Article 1590 du Code civil), de trente &agrave; cinquante pour cent (30&ndash;50 %) du prix total, imputable sur le prix en cas de confirmation.</p>\n<hr />\n<h2>ARTICLE 3 &mdash; DROIT DE R&Eacute;TRACTATION</h2>\n<p>Le d&eacute;lai de r&eacute;tractation de quatorze (14) jours (Article L.221-18 du Code de la consommation) court d&egrave;s l&rsquo;inscription et expire avant la confirmation du seuil. Le Client conserve son droit tant qu&rsquo;il n&rsquo;a acc&eacute;d&eacute; &agrave; aucun contenu num&eacute;rique.</p>\n<hr />\n<h2>ARTICLE 4 &mdash; SOLDE</h2>\n<p>Le solde est exigible sept (7) jours avant la premi&egrave;re Session Live confirm&eacute;e. &Agrave; d&eacute;faut de paiement apr&egrave;s mise en demeure de quarante-huit (48) heures, Acad&eacute;mIA Pro peut r&eacute;silier de plein droit, l&rsquo;acompte &eacute;tant conserv&eacute; &agrave; titre d&rsquo;indemnisation.</p>\n<hr />\n<h2>ARTICLE 5 &mdash; DROIT APPLICABLE</h2>\n<p>Le pr&eacute;sent avenant est r&eacute;gi par le droit fran&ccedil;ais. Les consommateurs de l&rsquo;UE b&eacute;n&eacute;ficient des dispositions protectrices de leur droit national (R&egrave;glement Rome I). Le droit du Wyoming (USA) s&rsquo;applique &agrave; titre suppl&eacute;tif hors UE.</p>\n<hr />\n<p><em>Avenant version 1.0 &mdash; &copy; Acad&eacute;mIA Pro LLC.</em></p>";
  return (
    <main style={{ maxWidth: 900, margin: "0 auto", padding: "48px 20px 80px", lineHeight: 1.7, fontSize: 16 }}>
      <style>{`
        .cgv h1 { font-size: 1.9rem; margin: 1.2em 0 .6em; }
        .cgv h2 { font-size: 1.35rem; margin: 2em 0 .6em; border-bottom: 1px solid rgba(128,128,128,.35); padding-bottom: .3em; }
        .cgv hr { border: none; border-top: 1px solid rgba(128,128,128,.35); margin: 2em 0; }
        .cgv a { color: #c9a227; }
      `}</style>
      <div className="cgv" dangerouslySetInnerHTML={{ __html: html }} />
    </main>
  );
}
