export default function PolitiqueConfidentialite() {
  const styles = {
    page: {
      backgroundColor: '#050508',
      color: '#e8e8e8',
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      minHeight: '100vh',
      padding: '0',
      margin: '0',
    } as React.CSSProperties,
    header: {
      backgroundColor: '#07070d',
      borderBottom: '1px solid #c8a96e33',
      padding: '48px 24px 40px',
      textAlign: 'center' as const,
    } as React.CSSProperties,
    badge: {
      display: 'inline-block',
      backgroundColor: '#c8a96e15',
      border: '1px solid #c8a96e44',
      color: '#c8a96e',
      fontSize: '12px',
      fontWeight: '600',
      letterSpacing: '2px',
      textTransform: 'uppercase' as const,
      padding: '6px 16px',
      borderRadius: '20px',
      marginBottom: '20px',
    } as React.CSSProperties,
    title: {
      fontSize: 'clamp(28px, 5vw, 48px)',
      fontWeight: '700',
      color: '#ffffff',
      margin: '0 0 12px',
      lineHeight: '1.2',
    } as React.CSSProperties,
    titleAccent: {
      color: '#c8a96e',
    } as React.CSSProperties,
    subtitle: {
      fontSize: '16px',
      color: '#999',
      margin: '0',
      maxWidth: '600px',
      marginLeft: 'auto',
      marginRight: 'auto',
    } as React.CSSProperties,
    updateDate: {
      display: 'inline-block',
      marginTop: '16px',
      fontSize: '13px',
      color: '#c8a96e99',
      backgroundColor: '#c8a96e0a',
      border: '1px solid #c8a96e22',
      padding: '4px 12px',
      borderRadius: '4px',
    } as React.CSSProperties,
    container: {
      maxWidth: '860px',
      margin: '0 auto',
      padding: '48px 24px 80px',
    } as React.CSSProperties,
    tocBox: {
      backgroundColor: '#0c0c14',
      border: '1px solid #c8a96e22',
      borderRadius: '12px',
      padding: '28px 32px',
      marginBottom: '48px',
    } as React.CSSProperties,
    tocTitle: {
      fontSize: '14px',
      fontWeight: '700',
      color: '#c8a96e',
      letterSpacing: '1.5px',
      textTransform: 'uppercase' as const,
      margin: '0 0 16px',
    } as React.CSSProperties,
    tocList: {
      listStyle: 'none',
      padding: '0',
      margin: '0',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
      gap: '8px',
    } as React.CSSProperties,
    tocItem: {
      fontSize: '14px',
      color: '#bbb',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      cursor: 'pointer',
      padding: '4px 0',
      transition: 'color 0.2s',
    } as React.CSSProperties,
    tocDot: {
      width: '6px',
      height: '6px',
      borderRadius: '50%',
      backgroundColor: '#c8a96e',
      flexShrink: 0,
    } as React.CSSProperties,
    section: {
      marginBottom: '48px',
      scrollMarginTop: '24px',
    } as React.CSSProperties,
    sectionHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
      marginBottom: '20px',
      paddingBottom: '16px',
      borderBottom: '1px solid #c8a96e22',
    } as React.CSSProperties,
    sectionNumber: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '36px',
      height: '36px',
      borderRadius: '8px',
      backgroundColor: '#c8a96e15',
      border: '1px solid #c8a96e33',
      color: '#c8a96e',
      fontSize: '14px',
      fontWeight: '700',
      flexShrink: 0,
    } as React.CSSProperties,
    sectionTitle: {
      fontSize: '22px',
      fontWeight: '700',
      color: '#ffffff',
      margin: '0',
    } as React.CSSProperties,
    paragraph: {
      fontSize: '15px',
      lineHeight: '1.8',
      color: '#ccc',
      margin: '0 0 16px',
    } as React.CSSProperties,
    highlightBox: {
      backgroundColor: '#0c0c14',
      border: '1px solid #c8a96e22',
      borderLeft: '3px solid #c8a96e',
      borderRadius: '0 8px 8px 0',
      padding: '16px 20px',
      margin: '16px 0',
    } as React.CSSProperties,
    highlightText: {
      fontSize: '14px',
      color: '#c8a96ecc',
      margin: '0',
      lineHeight: '1.6',
    } as React.CSSProperties,
    table: {
      width: '100%',
      borderCollapse: 'collapse' as const,
      fontSize: '14px',
      margin: '16px 0',
      borderRadius: '8px',
      overflow: 'hidden',
    } as React.CSSProperties,
    tableHeaderRow: {
      backgroundColor: '#c8a96e15',
    } as React.CSSProperties,
    th: {
      padding: '12px 16px',
      textAlign: 'left' as const,
      color: '#c8a96e',
      fontWeight: '600',
      fontSize: '13px',
      letterSpacing: '0.5px',
      borderBottom: '1px solid #c8a96e33',
    } as React.CSSProperties,
    td: {
      padding: '12px 16px',
      color: '#ccc',
      borderBottom: '1px solid #ffffff08',
      verticalAlign: 'top' as const,
      lineHeight: '1.5',
    } as React.CSSProperties,
    trEven: {
      backgroundColor: '#0c0c1499',
    } as React.CSSProperties,
    trOdd: {
      backgroundColor: '#07070d88',
    } as React.CSSProperties,
    list: {
      padding: '0 0 0 4px',
      margin: '12px 0',
      listStyle: 'none',
    } as React.CSSProperties,
    listItem: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '12px',
      fontSize: '15px',
      color: '#ccc',
      lineHeight: '1.7',
      marginBottom: '10px',
    } as React.CSSProperties,
    listBullet: {
      color: '#c8a96e',
      fontWeight: '700',
      flexShrink: 0,
      marginTop: '2px',
    } as React.CSSProperties,
    rightsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
      gap: '16px',
      margin: '16px 0',
    } as React.CSSProperties,
    rightCard: {
      backgroundColor: '#0c0c14',
      border: '1px solid #c8a96e22',
      borderRadius: '10px',
      padding: '20px',
    } as React.CSSProperties,
    rightCardIcon: {
      fontSize: '24px',
      marginBottom: '10px',
      display: 'block',
    } as React.CSSProperties,
    rightCardTitle: {
      fontSize: '14px',
      fontWeight: '700',
      color: '#c8a96e',
      margin: '0 0 8px',
    } as React.CSSProperties,
    rightCardDesc: {
      fontSize: '13px',
      color: '#999',
      margin: '0',
      lineHeight: '1.5',
    } as React.CSSProperties,
    cookieTag: {
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: '4px',
      fontSize: '12px',
      fontWeight: '600',
    } as React.CSSProperties,
    cookieTagNecessaire: {
      backgroundColor: '#22c55e15',
      color: '#22c55e',
      border: '1px solid #22c55e33',
    } as React.CSSProperties,
    cookieTagAnalytique: {
      backgroundColor: '#3b82f615',
      color: '#3b82f6',
      border: '1px solid #3b82f633',
    } as React.CSSProperties,
    cookieTagMarketing: {
      backgroundColor: '#f59e0b15',
      color: '#f59e0b',
      border: '1px solid #f59e0b33',
    } as React.CSSProperties,
    contactBox: {
      backgroundColor: '#0c0c14',
      border: '1px solid #c8a96e33',
      borderRadius: '12px',
      padding: '28px 32px',
      margin: '16px 0',
    } as React.CSSProperties,
    contactEmail: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      color: '#c8a96e',
      fontSize: '16px',
      fontWeight: '600',
      textDecoration: 'none',
      backgroundColor: '#c8a96e10',
      border: '1px solid #c8a96e33',
      padding: '10px 18px',
      borderRadius: '8px',
      marginTop: '12px',
    } as React.CSSProperties,
    cnilBox: {
      backgroundColor: '#c8a96e08',
      border: '1px solid #c8a96e33',
      borderRadius: '10px',
      padding: '20px 24px',
      margin: '16px 0',
    } as React.CSSProperties,
    cnilText: {
      fontSize: '14px',
      color: '#bbb',
      margin: '0 0 8px',
      lineHeight: '1.6',
    } as React.CSSProperties,
    cnilLink: {
      color: '#c8a96e',
      textDecoration: 'none',
      fontWeight: '600',
    } as React.CSSProperties,
    footer: {
      backgroundColor: '#07070d',
      borderTop: '1px solid #c8a96e22',
      padding: '32px 24px',
      textAlign: 'center' as const,
    } as React.CSSProperties,
    footerText: {
      fontSize: '13px',
      color: '#666',
      margin: '0 0 8px',
    } as React.CSSProperties,
    footerBrand: {
      fontSize: '16px',
      fontWeight: '700',
      color: '#c8a96e',
    } as React.CSSProperties,
    divider: {
      height: '1px',
      backgroundColor: '#c8a96e11',
      margin: '8px 0 48px',
    } as React.CSSProperties,
  };

  const collecteeData = [
    { categorie: 'Données d\'identité', exemples: 'Nom, prénom, adresse email', obligatoire: 'Oui' },
    { categorie: 'Données de connexion', exemples: 'Adresse IP, logs de session, horodatage', obligatoire: 'Oui' },
    { categorie: 'Données pédagogiques', exemples: 'Exercices soumis, scores, progression, historique IA', obligatoire: 'Oui' },
    { categorie: 'Données de paiement', exemples: 'Référence de transaction, dernier chiffres carte (via Stripe)', obligatoire: 'Conditionnelle' },
    { categorie: 'Données de profil', exemples: 'Niveau scolaire, matières, préférences d\'apprentissage', obligatoire: 'Non' },
    { categorie: 'Données de communication', exemples: 'Emails reçus/ouverts (via Resend)', obligatoire: 'Non' },
    { categorie: 'Données de navigation', exemples: 'Pages visitées, clics, durée de session', obligatoire: 'Non' },
  ];

  const finalitesData = [
    { finalite: 'Fourniture du service', description: 'Accès à la plateforme, génération de contenus pédagogiques par IA', base: 'Exécution du contrat' },
    { finalite: 'Gestion des comptes', description: 'Création, authentification, sécurité des comptes utilisateurs', base: 'Exécution du contrat' },
    { finalite: 'Facturation & paiement', description: 'Traitement des abonnements, émission de factures', base: 'Obligation légale' },
    { finalite: 'Communication transactionnelle', description: 'Emails de confirmation, alertes de sécurité, notifications essentielles', base: 'Exécution du contrat' },
    { finalite: 'Amélioration du service', description: 'Analyse des usages pour améliorer les algorithmes pédagogiques', base: 'Intérêt légitime' },
    { finalite: 'Marketing & newsletters', description: 'Envoi d\'offres, actualités, conseils pédagogiques', base: 'Consentement' },
    { finalite: 'Conformité légale', description: 'Respect des obligations comptables et fiscales', base: 'Obligation légale' },
    { finalite: 'Prévention des fraudes', description: 'Détection d\'activités suspectes et sécurisation de la plateforme', base: 'Intérêt légitime' },
  ];

  const dureeData = [
    { donnee: 'Données de compte actif', duree: 'Durée de la relation contractuelle' },
    { donnee: 'Données après suppression de compte', duree: '30 jours (purge complète), sauf obligation légale' },
    { donnee: 'Données pédagogiques et exercices', duree: 'Durée de l\'abonnement + 12 mois' },
    { donnee: 'Données de facturation', duree: '10 ans (obligation comptable française)' },
    { donnee: 'Logs de connexion et sécurité', duree: '12 mois' },
    { donnee: '