import React from 'react';

const AboutPage: React.FC = () => {
  const styles = {
    page: {
      backgroundColor: '#050508',
      minHeight: '100vh',
      fontFamily: "'Segoe UI', system-ui, sans-serif",
      color: '#ffffff',
      overflowX: 'hidden' as const,
    },
    heroSection: {
      position: 'relative' as const,
      padding: '100px 24px 80px',
      textAlign: 'center' as const,
      background: 'linear-gradient(180deg, #0d0d18 0%, #050508 100%)',
    },
    badge: {
      display: 'inline-block',
      backgroundColor: 'rgba(200, 169, 110, 0.12)',
      border: '1px solid rgba(200, 169, 110, 0.4)',
      color: '#c8a96e',
      fontSize: '12px',
      fontWeight: '600' as const,
      letterSpacing: '3px',
      textTransform: 'uppercase' as const,
      padding: '8px 20px',
      borderRadius: '50px',
      marginBottom: '32px',
    },
    heroTitle: {
      fontSize: 'clamp(36px, 6vw, 72px)',
      fontWeight: '800' as const,
      lineHeight: '1.1',
      margin: '0 auto 24px',
      maxWidth: '800px',
    },
    titleSpan: {
      background: 'linear-gradient(135deg, #c8a96e 0%, #f0d5a0 50%, #c8a96e 100%)',
      WebkitBackgroundClip: 'text' as const,
      WebkitTextFillColor: 'transparent' as const,
      backgroundClip: 'text' as const,
    },
    heroSubtitle: {
      fontSize: '18px',
      color: 'rgba(255,255,255,0.6)',
      maxWidth: '600px',
      margin: '0 auto',
      lineHeight: '1.7',
    },
    decorLine: {
      width: '60px',
      height: '3px',
      background: 'linear-gradient(90deg, #c8a96e, #f0d5a0)',
      margin: '40px auto 0',
      borderRadius: '2px',
    },
    section: {
      padding: '80px 24px',
      maxWidth: '1100px',
      margin: '0 auto',
    },
    sectionLabel: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      marginBottom: '16px',
    },
    sectionLabelLine: {
      width: '32px',
      height: '2px',
      backgroundColor: '#c8a96e',
      borderRadius: '2px',
    },
    sectionLabelText: {
      color: '#c8a96e',
      fontSize: '12px',
      fontWeight: '700' as const,
      letterSpacing: '3px',
      textTransform: 'uppercase' as const,
    },
    sectionTitle: {
      fontSize: 'clamp(28px, 4vw, 44px)',
      fontWeight: '700' as const,
      lineHeight: '1.2',
      marginBottom: '20px',
      color: '#ffffff',
    },
    sectionText: {
      fontSize: '16px',
      color: 'rgba(255,255,255,0.6)',
      lineHeight: '1.8',
      maxWidth: '600px',
    },
    missionCard: {
      background: 'linear-gradient(135deg, rgba(200,169,110,0.08) 0%, rgba(200,169,110,0.03) 100%)',
      border: '1px solid rgba(200,169,110,0.2)',
      borderRadius: '24px',
      padding: '48px',
      position: 'relative' as const,
      overflow: 'hidden' as const,
    },
    missionGlow: {
      position: 'absolute' as const,
      top: '-80px',
      right: '-80px',
      width: '300px',
      height: '300px',
      background: 'radial-gradient(circle, rgba(200,169,110,0.08) 0%, transparent 70%)',
      borderRadius: '50%',
      pointerEvents: 'none' as const,
    },
    missionGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
      gap: '32px',
      marginTop: '48px',
    },
    missionItem: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '12px',
    },
    missionIcon: {
      width: '48px',
      height: '48px',
      borderRadius: '12px',
      backgroundColor: 'rgba(200,169,110,0.1)',
      border: '1px solid rgba(200,169,110,0.25)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '22px',
    },
    missionItemTitle: {
      fontSize: '18px',
      fontWeight: '700' as const,
      color: '#ffffff',
    },
    missionItemText: {
      fontSize: '15px',
      color: 'rgba(255,255,255,0.55)',
      lineHeight: '1.7',
    },
    divider: {
      width: '100%',
      height: '1px',
      background: 'linear-gradient(90deg, transparent, rgba(200,169,110,0.2), transparent)',
      margin: '0 24px',
      maxWidth: '1100px',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    statsSection: {
      padding: '80px 24px',
      background: 'linear-gradient(180deg, rgba(200,169,110,0.03) 0%, transparent 100%)',
    },
    statsInner: {
      maxWidth: '1100px',
      margin: '0 auto',
    },
    statsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: '24px',
      marginTop: '48px',
    },
    statCard: {
      background: 'rgba(255,255,255,0.02)',
      border: '1px solid rgba(200,169,110,0.15)',
      borderRadius: '20px',
      padding: '36px 24px',
      textAlign: 'center' as const,
      position: 'relative' as const,
      overflow: 'hidden' as const,
      transition: 'border-color 0.3s',
    },
    statCardAccent: {
      position: 'absolute' as const,
      bottom: '0',
      left: '0',
      right: '0',
      height: '2px',
      background: 'linear-gradient(90deg, transparent, #c8a96e, transparent)',
    },
    statNumber: {
      fontSize: '54px',
      fontWeight: '800' as const,
      background: 'linear-gradient(135deg, #c8a96e 0%, #f0d5a0 100%)',
      WebkitBackgroundClip: 'text' as const,
      WebkitTextFillColor: 'transparent' as const,
      backgroundClip: 'text' as const,
      lineHeight: '1',
      marginBottom: '8px',
    },
    statLabel: {
      fontSize: '13px',
      color: 'rgba(255,255,255,0.5)',
      fontWeight: '600' as const,
      letterSpacing: '1.5px',
      textTransform: 'uppercase' as const,
    },
    valuesSection: {
      padding: '80px 24px',
      maxWidth: '1100px',
      margin: '0 auto',
    },
    valuesGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
      gap: '20px',
      marginTop: '48px',
    },
    valueCard: {
      background: 'rgba(255,255,255,0.02)',
      border: '1px solid rgba(255,255,255,0.06)',
      borderRadius: '20px',
      padding: '36px 32px',
      transition: 'border-color 0.3s',
    },
    valueNumber: {
      fontSize: '48px',
      fontWeight: '900' as const,
      color: 'rgba(200,169,110,0.08)',
      lineHeight: '1',
      marginBottom: '16px',
      fontFamily: 'Georgia, serif',
    },
    valueTitle: {
      fontSize: '20px',
      fontWeight: '700' as const,
      color: '#ffffff',
      marginBottom: '12px',
      letterSpacing: '0.5px',
    },
    valueDash: {
      width: '24px',
      height: '2px',
      backgroundColor: '#c8a96e',
      borderRadius: '2px',
      marginBottom: '16px',
    },
    valueText: {
      fontSize: '15px',
      color: 'rgba(255,255,255,0.55)',
      lineHeight: '1.7',
    },
    visionSection: {
      padding: '80px 24px',
      background: 'linear-gradient(180deg, transparent, rgba(200,169,110,0.04) 50%, transparent 100%)',
    },
    visionInner: {
      maxWidth: '1100px',
      margin: '0 auto',
    },
    visionCard: {
      background: 'linear-gradient(135deg, rgba(200,169,110,0.06) 0%, rgba(5,5,8,0.8) 100%)',
      border: '1px solid rgba(200,169,110,0.25)',
      borderRadius: '28px',
      padding: '64px',
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '64px',
      alignItems: 'center',
      position: 'relative' as const,
      overflow: 'hidden' as const,
    },
    visionGlow1: {
      position: 'absolute' as const,
      top: '-100px',
      left: '-100px',
      width: '400px',
      height: '400px',
      background: 'radial-gradient(circle, rgba(200,169,110,0.06) 0%, transparent 70%)',
      borderRadius: '50%',
      pointerEvents: 'none' as const,
    },
    visionGlow2: {
      position: 'absolute' as const,
      bottom: '-100px',
      right: '-100px',
      width: '400px',
      height: '400px',
      background: 'radial-gradient(circle, rgba(200,169,110,0.04) 0%, transparent 70%)',
      borderRadius: '50%',
      pointerEvents: 'none' as const,
    },
    visionTextBlock: {
      position: 'relative' as const,
      zIndex: 1,
    },
    visionBigText: {
      fontSize: 'clamp(32px, 4vw, 48px)',
      fontWeight: '800' as const,
      lineHeight: '1.2',
      marginBottom: '24px',
    },
    visionDesc: {
      fontSize: '16px',
      color: 'rgba(255,255,255,0.6)',
      lineHeight: '1.8',
    },
    visionFeatures: {
      position: 'relative' as const,
      zIndex: 1,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '20px',
    },
    visionFeatureItem: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '16px',
      padding: '20px',
      background: 'rgba(255,255,255,0.03)',
      border: '1px solid rgba(255,255,255,0.06)',
      borderRadius: '14px',
    },
    visionFeatureIcon: {
      width: '40px',
      height: '40px',
      minWidth: '40px',
      borderRadius: '10px',
      backgroundColor: 'rgba(200,169,110,0.1)',
      border: '1px solid rgba(200,169,110,0.2)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '18px',
    },
    visionFeatureContent: {
      flex: 1,
    },
    visionFeatureTitle: {
      fontSize: '15px',
      fontWeight: '700' as const,
      color: '#ffffff',
      marginBottom: '4px',
    },
    visionFeatureText: {
      fontSize: '13px',
      color: 'rgba(255,255,255,0.5)',
      lineHeight: '1.6',
    },
    ctaSection: {
      padding: '80px 24px 120px',
      textAlign: 'center' as const,
    },
    ctaCard: {
      maxWidth: '700px',
      margin: '0 auto',
      padding: '64px 48px',
      background: 'rgba(200,169,110,0.04)',
      border: '1px solid rgba(200,169,110,0.2)',
      borderRadius: '28px',
    },
    ctaTitle: {
      fontSize: 'clamp(28px, 4vw, 40px)',
      fontWeight: '800' as const,
      marginBottom: '16px',
      lineHeight: '1.2',
    },
    ctaText: {
      fontSize: '16px',
      color: 'rgba(255,255,255,0.6)',
      lineHeight: '1.7',
      marginBottom: '36px',
    },
    ctaButton: {
      display: 'inline-block',
      background: 'linear-gradient(135deg, #c8a96e 0%, #f0d5a0 50%, #c8a96e 100%)',
      color: '#050508',
      fontSize: '15px',
      fontWeight: '700' as const,
      padding: '16px 40px',
      borderRadius: '50px',
      textDecoration: 'none',
      letterSpacing: '0.5px',
      cursor: 'pointer',
      border: 'none',
      backgroundSize: '200% auto',
    },
    footerText: {
      textAlign: 'center' as const,
      padding: '32px 24px',
      borderTop: '1px solid rgba(255,255,255,0.05)',
      color: 'rgba(255,255,255,0.25)',
      fontSize: '13px',
    },
  };

  const stats = [
    { number: '131', label: 'Formations' },
    { number: '20', label: 'Skills' },
    { number: '14', label: 'Spécialités