export default function MonEspace() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      backgroundColor: "#050508",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      color: "#e8e0d0",
      padding: "0",
      margin: "0",
    },
    header: {
      backgroundColor: "#0a0a0f",
      borderBottom: "1px solid #c8a96e33",
      padding: "16px 32px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      position: "sticky" as const,
      top: 0,
      zIndex: 100,
      backdropFilter: "blur(12px)",
    },
    logo: {
      fontSize: "22px",
      fontWeight: "800",
      color: "#c8a96e",
      letterSpacing: "0.5px",
    },
    logoSub: {
      fontSize: "11px",
      color: "#888",
      letterSpacing: "2px",
      textTransform: "uppercase" as const,
      marginTop: "2px",
    },
    headerNav: {
      display: "flex",
      gap: "8px",
      alignItems: "center",
    },
    navLink: {
      color: "#c8a96e",
      textDecoration: "none",
      fontSize: "13px",
      padding: "8px 16px",
      borderRadius: "8px",
      border: "1px solid #c8a96e44",
      transition: "all 0.2s",
      backgroundColor: "transparent",
      cursor: "pointer",
    },
    navLinkPrimary: {
      color: "#050508",
      textDecoration: "none",
      fontSize: "13px",
      padding: "8px 16px",
      borderRadius: "8px",
      backgroundColor: "#c8a96e",
      fontWeight: "600",
      cursor: "pointer",
    },
    avatar: {
      width: "38px",
      height: "38px",
      borderRadius: "50%",
      backgroundColor: "#c8a96e22",
      border: "2px solid #c8a96e",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "16px",
      cursor: "pointer",
    },
    main: {
      maxWidth: "1280px",
      margin: "0 auto",
      padding: "40px 32px",
    },
    welcomeBanner: {
      background: "linear-gradient(135deg, #0f0f1a 0%, #1a1408 50%, #0f0f1a 100%)",
      border: "1px solid #c8a96e33",
      borderRadius: "16px",
      padding: "32px 40px",
      marginBottom: "40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      position: "relative" as const,
      overflow: "hidden",
    },
    welcomeGlow: {
      position: "absolute" as const,
      top: "-60px",
      right: "-60px",
      width: "200px",
      height: "200px",
      background: "radial-gradient(circle, #c8a96e22 0%, transparent 70%)",
      pointerEvents: "none" as const,
    },
    welcomeTitle: {
      fontSize: "28px",
      fontWeight: "700",
      color: "#e8e0d0",
      marginBottom: "6px",
    },
    welcomeGold: {
      color: "#c8a96e",
    },
    welcomeSub: {
      fontSize: "14px",
      color: "#888",
      marginBottom: "20px",
    },
    statsRow: {
      display: "flex",
      gap: "24px",
      flexWrap: "wrap" as const,
    },
    statBadge: {
      display: "flex",
      flexDirection: "column" as const,
      alignItems: "center",
      backgroundColor: "#c8a96e11",
      border: "1px solid #c8a96e33",
      borderRadius: "12px",
      padding: "14px 20px",
      minWidth: "90px",
    },
    statValue: {
      fontSize: "24px",
      fontWeight: "800",
      color: "#c8a96e",
    },
    statLabel: {
      fontSize: "11px",
      color: "#888",
      textTransform: "uppercase" as const,
      letterSpacing: "1px",
      marginTop: "2px",
      textAlign: "center" as const,
    },
    memberBadge: {
      backgroundColor: "#c8a96e",
      color: "#050508",
      padding: "8px 20px",
      borderRadius: "24px",
      fontSize: "13px",
      fontWeight: "700",
      letterSpacing: "0.5px",
      textAlign: "center" as const,
    },
    memberSince: {
      fontSize: "12px",
      color: "#666",
      marginTop: "8px",
      textAlign: "center" as const,
    },
    grid2: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "24px",
      marginBottom: "24px",
    },
    grid3: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr",
      gap: "24px",
      marginBottom: "24px",
    },
    card: {
      backgroundColor: "#0a0a0f",
      border: "1px solid #1e1e2e",
      borderRadius: "16px",
      padding: "28px",
      marginBottom: "0",
    },
    cardFull: {
      backgroundColor: "#0a0a0f",
      border: "1px solid #1e1e2e",
      borderRadius: "16px",
      padding: "28px",
      marginBottom: "24px",
    },
    cardTitle: {
      fontSize: "16px",
      fontWeight: "700",
      color: "#e8e0d0",
      marginBottom: "20px",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    cardTitleIcon: {
      fontSize: "18px",
    },
    cardTitleBadge: {
      backgroundColor: "#c8a96e22",
      color: "#c8a96e",
      fontSize: "11px",
      padding: "3px 10px",
      borderRadius: "20px",
      fontWeight: "600",
      marginLeft: "auto",
    },
    formationItem: {
      display: "flex",
      gap: "16px",
      alignItems: "flex-start",
      padding: "16px",
      backgroundColor: "#050508",
      borderRadius: "12px",
      marginBottom: "12px",
      border: "1px solid #1e1e2e",
      cursor: "pointer",
    },
    formationThumb: {
      width: "64px",
      height: "64px",
      borderRadius: "10px",
      flexShrink: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "24px",
    },
    formationInfo: {
      flex: 1,
    },
    formationTitle: {
      fontSize: "14px",
      fontWeight: "600",
      color: "#e8e0d0",
      marginBottom: "4px",
    },
    formationMeta: {
      fontSize: "12px",
      color: "#666",
      marginBottom: "10px",
    },
    progressBarWrap: {
      backgroundColor: "#1e1e2e",
      borderRadius: "4px",
      height: "6px",
      overflow: "hidden",
    },
    progressBarFill: (pct: number) => ({
      height: "100%",
      width: `${pct}%`,
      background: "linear-gradient(90deg, #c8a96e, #e8c882)",
      borderRadius: "4px",
      transition: "width 0.6s ease",
    }),
    progressPct: {
      fontSize: "12px",
      color: "#c8a96e",
      fontWeight: "600",
      marginTop: "4px",
    },
    resumeBtn: {
      backgroundColor: "#c8a96e",
      color: "#050508",
      border: "none",
      borderRadius: "8px",
      padding: "7px 14px",
      fontSize: "12px",
      fontWeight: "700",
      cursor: "pointer",
      flexShrink: 0,
      marginTop: "4px",
    },
    certCard: {
      backgroundColor: "#050508",
      border: "1px solid #c8a96e33",
      borderRadius: "12px",
      padding: "20px",
      marginBottom: "12px",
      display: "flex",
      alignItems: "center",
      gap: "16px",
    },
    certIcon: {
      fontSize: "32px",
      flexShrink: 0,
    },
    certInfo: {
      flex: 1,
    },
    certTitle: {
      fontSize: "14px",
      fontWeight: "600",
      color: "#e8e0d0",
      marginBottom: "3px",
    },
    certDate: {
      fontSize: "12px",
      color: "#666",
    },
    certActions: {
      display: "flex",
      gap: "8px",
    },
    certBtn: {
      backgroundColor: "transparent",
      border: "1px solid #c8a96e44",
      color: "#c8a96e",
      borderRadius: "8px",
      padding: "6px 12px",
      fontSize: "12px",
      cursor: "pointer",
    },
    seanceItem: {
      display: "flex",
      gap: "16px",
      alignItems: "center",
      padding: "14px 16px",
      backgroundColor: "#050508",
      borderRadius: "12px",
      marginBottom: "10px",
      border: "1px solid #1e1e2e",
    },
    seanceDateBox: {
      backgroundColor: "#c8a96e11",
      border: "1px solid #c8a96e33",
      borderRadius: "10px",
      padding: "10px 14px",
      textAlign: "center" as const,
      flexShrink: 0,
      minWidth: "52px",
    },
    seanceDay: {
      fontSize: "20px",
      fontWeight: "800",
      color: "#c8a96e",
      lineHeight: "1",
    },
    seanceMois: {
      fontSize: "10px",
      color: "#888",
      textTransform: "uppercase" as const,
      letterSpacing: "1px",
    },
    seanceInfo: {
      flex: 1,
    },
    seanceTitle: {
      fontSize: "14px",
      fontWeight: "600",
      color: "#e8e0d0",
      marginBottom: "3px",
    },
    seanceMeta: {
      fontSize: "12px",
      color: "#666",
    },
    seanceTag: {
      backgroundColor: "#1e3a1e",
      color: "#4ade80",
      fontSize: "11px",
      padding: "4px 10px",
      borderRadius: "6px",
      fontWeight: "600",
    },
    seanceTagLive: {
      backgroundColor: "#3a1e1e",
      color: "#f87171",
      fontSize: "11px",
      padding: "4px 10px",
      borderRadius: "6px",
      fontWeight: "600",
    },
    paymentTable: {
      width: "100%",
      borderCollapse: "collapse" as const,
    },
    paymentTh: {
      textAlign: "left" as const,
      fontSize: "11px",
      color: "#666",
      textTransform: "uppercase" as const,
      letterSpacing: "1px",
      paddingBottom: "12px",
      borderBottom: "1px solid #1e1e2e",
    },
    paymentTd: {
      padding: "14px 0",
      fontSize: "13px",
      color: "#c8c0b0",
      borderBottom: "1px solid #0f0f18",
      verticalAlign: "middle" as const,
    },
    paymentStatus: (ok: boolean) => ({
      backgroundColor: ok ? "#1e3a1e" : "#3a1e1e",
      color: ok ? "#4ade80" : "#f87171",
      fontSize: "11px",
      padding: "4px 10px",
      borderRadius: "6px",
      fontWeight: "600",
      display: "inline-block",
    }),
    paymentAmount: {
      color: "#c8a96e",
      fontWeight: "700",
      fontSize: "14px",
    },
    downloadBtn: {
      backgroundColor: "transparent",
      border: "1px solid #c8a96e33",
      color: "#c8a96e",
      borderRadius: "6px",
      padding: "4px 10px",
      fontSize: "11px",
      cursor: "pointer",
    },
    profileGrid: {
      display: "grid",
      gridTemplateColumns: "auto 1fr",
      gap: "24px",
      alignItems: "start",
    },
    profileAvatar: {
      width: "80px",
      height: "80px",
      borderRadius: "50%",
      backgroundColor: "#c8a96e22",
      border: "3px solid #c8a96e",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "32px",
      position: "relative" as const,
      cursor: "pointer",
    },
    profileAvatarEdit: {
      position: "absolute" as const,
      bottom: "0",
      right: "0",
      backgroundColor: "#c8a96e",
      color: "#050508",
      width: "22px",
      height: "22px",
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "11px",
    },
    profileFields: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "14px",
    },
    fieldGroup: {
      display: "flex",
      flexDirection: "column" as const,
      gap: "6px",
    },
    fieldLabel: {
      fontSize: "11px",
      color: "#666",
      textTransform: "uppercase" as const,
      letterSpacing: "1px",
    },
    fieldValue: {
      fontSize: "14px",
      color: "#e8e0d0",
      backgroundColor: "#050508",
      border: "1px solid #1e1e2e",
      borderRadius: "8px",
      padding: "10px 14px",
    },
    fieldInput: {
      fontSize: "14px",
      color: "#e8e0d0",
      backgroundColor: "#050508",
      border: "1px solid #c8a