"use client";
import { useLangue } from "./LangueSwitcher";

const TRADUCTIONS: Record<string, Record<string, string>> = {
  fr: {
    nav_formations: "Formations",
    nav_seances: "Séances",
    nav_blog: "Blog",
    nav_contact: "Contact",
    hero_titre: "Formez-vous avec votre agent IA personnel",
    hero_sous_titre: "235 formations certifiantes · Agent IA tuteur 24h/24 · Séances thérapeutiques",
    btn_voir_formations: "Voir les formations",
    btn_demarrer: "Démarrer",
    stat_formations: "Formations certifiantes",
    stat_competences: "Compétences validées",
    stat_therapeutes: "Thérapeutes IA",
    stat_garantie: "Garantie satisfait",
    catalogue_titre: "Catalogue AcadémIA Pro",
    inscription_titre: "Rejoignez la Liste Prioritaire",
  },
  en: {
    nav_formations: "Courses",
    nav_seances: "Sessions",
    nav_blog: "Blog",
    nav_contact: "Contact",
    hero_titre: "Learn with your personal AI agent",
    hero_sous_titre: "235 certified courses · AI tutor 24/7 · Therapeutic sessions",
    btn_voir_formations: "View courses",
    btn_demarrer: "Get Started",
    stat_formations: "Certified courses",
    stat_competences: "Validated skills",
    stat_therapeutes: "AI Therapists",
    stat_garantie: "Satisfaction guarantee",
    catalogue_titre: "AcadémIA Pro Catalog",
    inscription_titre: "Join the Priority List",
  },
  es: {
    nav_formations: "Cursos",
    nav_seances: "Sesiones",
    nav_blog: "Blog",
    nav_contact: "Contacto",
    hero_titre: "Formese con su agente IA personal",
    hero_sous_titre: "235 cursos certificados · Tutor IA 24h · Sesiones terapeuticas",
    btn_voir_formations: "Ver cursos",
    btn_demarrer: "Comenzar",
    stat_formations: "Cursos certificados",
    stat_competences: "Habilidades validadas",
    stat_therapeutes: "Terapeutas IA",
    stat_garantie: "Garantia satisfaccion",
    catalogue_titre: "Catalogo AcadémIA Pro",
    inscription_titre: "Unase a la Lista Prioritaria",
  },
  ar: {
    nav_formations: "الدورات",
    nav_seances: "الجلسات",
    nav_blog: "المدونة",
    nav_contact: "اتصل بنا",
    hero_titre: "تدرب مع وكيل الذكاء الاصطناعي الشخصي",
    hero_sous_titre: "235 دورة معتمدة · مدرس ذكاء اصطناعي · جلسات علاجية",
    btn_voir_formations: "عرض الدورات",
    btn_demarrer: "ابدأ",
    stat_formations: "دورات معتمدة",
    stat_competences: "مهارات معتمدة",
    stat_therapeutes: "معالجون AI",
    stat_garantie: "ضمان الرضا",
    catalogue_titre: "كتالوج AcadémIA Pro",
    inscription_titre: "انضم إلى قائمة الأولوية",
  },
  he: {
    nav_formations: "קורסים",
    nav_seances: "פגישות",
    nav_blog: "בלוג",
    nav_contact: "צור קשר",
    hero_titre: "התאמן עם סוכן הבינה המלאכותית האישי שלך",
    hero_sous_titre: "235 קורסים מוסמכים · מדריך AI 24/7 · פגישות טיפוליות",
    btn_voir_formations: "צפה בקורסים",
    btn_demarrer: "התחל",
    stat_formations: "קורסים מוסמכים",
    stat_competences: "כישורים מאומתים",
    stat_therapeutes: "מטפלים AI",
    stat_garantie: "ערובת שביעות רצון",
    catalogue_titre: "קטלוג AcadémIA Pro",
    inscription_titre: "הצטרף לרשימת העדיפות",
  },
};

export function useT() {
  const { langue } = useLangue();
  return (cle: string) => TRADUCTIONS[langue]?.[cle] || TRADUCTIONS["fr"][cle] || cle;
}
