export default function FinancementPage() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      backgroundColor: "#050508",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      color: "#ffffff",
      overflowX: "hidden",
    },
    container: {
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "0 24px",
    },
    header: {
      padding: "80px 24px 60px",
      textAlign: "center",
      borderBottom: "1px solid rgba(200, 169, 110, 0.15)",
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      backgroundColor: "rgba(200, 169, 110, 0.1)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      borderRadius: "50px",
      padding: "8px 20px",
      fontSize: "13px",
      color: "#c8a96e",
      marginBottom: "32px",
      letterSpacing: "0.5px",
      textTransform: "uppercase" as const,
    },
    badgeDot: {
      width: "6px",
      height: "6px",
      borderRadius: "50%",
      backgroundColor: "#c8a96e",
      boxShadow: "0 0 8px #c8a96e",
    },
    heroTitle: {
      fontSize: "clamp(36px, 5vw, 64px)",
      fontWeight: "800",
      lineHeight: "1.1",
      marginBottom: "24px",
      letterSpacing: "-1px",
    },
    goldText: {
      color: "#c8a96e",
      backgroundImage: "linear-gradient(135deg, #c8a96e 0%, #e8d5a3 50%, #c8a96e 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
    },
    heroSubtitle: {
      fontSize: "18px",
      color: "rgba(255,255,255,0.6)",
      maxWidth: "600px",
      margin: "0 auto",
      lineHeight: "1.7",
    },
    section: {
      padding: "80px 24px",
    },
    sectionTitle: {
      fontSize: "32px",
      fontWeight: "700",
      marginBottom: "12px",
      color: "#ffffff",
    },
    sectionSubtitle: {
      fontSize: "16px",
      color: "rgba(255,255,255,0.5)",
      marginBottom: "48px",
    },
    sectionHeader: {
      textAlign: "center",
      marginBottom: "56px",
    },
    divider: {
      width: "60px",
      height: "3px",
      backgroundImage: "linear-gradient(90deg, #c8a96e, transparent)",
      borderRadius: "2px",
      margin: "16px auto 0",
    },
    grid3: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
      gap: "24px",
    },
    grid2: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
      gap: "32px",
    },
    card: {
      backgroundColor: "rgba(255,255,255,0.03)",
      border: "1px solid rgba(200, 169, 110, 0.12)",
      borderRadius: "20px",
      padding: "36px",
      position: "relative" as const,
      transition: "transform 0.2s ease",
      overflow: "hidden",
    },
    cardFeatured: {
      backgroundColor: "rgba(200, 169, 110, 0.06)",
      border: "1px solid rgba(200, 169, 110, 0.4)",
      borderRadius: "20px",
      padding: "36px",
      position: "relative" as const,
      overflow: "hidden",
    },
    cardGlow: {
      position: "absolute" as const,
      top: "0",
      right: "0",
      width: "200px",
      height: "200px",
      background: "radial-gradient(circle, rgba(200,169,110,0.08) 0%, transparent 70%)",
      pointerEvents: "none" as const,
    },
    featuredBadge: {
      position: "absolute" as const,
      top: "20px",
      right: "20px",
      backgroundColor: "#c8a96e",
      color: "#050508",
      fontSize: "11px",
      fontWeight: "700",
      padding: "4px 12px",
      borderRadius: "50px",
      letterSpacing: "0.5px",
      textTransform: "uppercase" as const,
    },
    paymentIcon: {
      width: "52px",
      height: "52px",
      borderRadius: "14px",
      backgroundColor: "rgba(200, 169, 110, 0.1)",
      border: "1px solid rgba(200, 169, 110, 0.2)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "24px",
      marginBottom: "24px",
    },
    cardTitle: {
      fontSize: "22px",
      fontWeight: "700",
      marginBottom: "8px",
      color: "#ffffff",
    },
    cardDesc: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.5)",
      marginBottom: "28px",
      lineHeight: "1.6",
    },
    priceDisplay: {
      marginBottom: "28px",
    },
    priceMain: {
      fontSize: "42px",
      fontWeight: "800",
      color: "#c8a96e",
      lineHeight: "1",
    },
    priceSub: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.4)",
      marginTop: "6px",
    },
    featureList: {
      listStyle: "none",
      padding: "0",
      margin: "0 0 32px",
      display: "flex",
      flexDirection: "column" as const,
      gap: "12px",
    },
    featureItem: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      fontSize: "14px",
      color: "rgba(255,255,255,0.75)",
    },
    featureCheck: {
      width: "18px",
      height: "18px",
      borderRadius: "50%",
      backgroundColor: "rgba(200, 169, 110, 0.15)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "10px",
      color: "#c8a96e",
      flexShrink: 0,
    },
    btnPrimary: {
      width: "100%",
      padding: "14px 24px",
      backgroundImage: "linear-gradient(135deg, #c8a96e 0%, #e8d5a3 50%, #b8994e 100%)",
      color: "#050508",
      border: "none",
      borderRadius: "12px",
      fontSize: "15px",
      fontWeight: "700",
      cursor: "pointer",
      letterSpacing: "0.3px",
    },
    btnSecondary: {
      width: "100%",
      padding: "14px 24px",
      backgroundColor: "transparent",
      color: "#c8a96e",
      border: "1px solid rgba(200, 169, 110, 0.4)",
      borderRadius: "12px",
      fontSize: "15px",
      fontWeight: "600",
      cursor: "pointer",
      letterSpacing: "0.3px",
    },
    separator: {
      height: "1px",
      backgroundColor: "rgba(200, 169, 110, 0.08)",
      margin: "0 24px",
    },
    enterpriseSection: {
      padding: "80px 24px",
      backgroundColor: "rgba(200, 169, 110, 0.02)",
    },
    enterpriseCard: {
      backgroundColor: "rgba(255,255,255,0.02)",
      border: "1px solid rgba(200, 169, 110, 0.15)",
      borderRadius: "20px",
      padding: "40px",
      display: "flex",
      flexDirection: "column" as const,
      gap: "24px",
    },
    enterpriseCardTop: {
      display: "flex",
      alignItems: "flex-start",
      gap: "20px",
    },
    enterpriseIcon: {
      width: "56px",
      height: "56px",
      borderRadius: "16px",
      backgroundColor: "rgba(200, 169, 110, 0.1)",
      border: "1px solid rgba(200, 169, 110, 0.25)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "26px",
      flexShrink: 0,
    },
    enterpriseCardTitle: {
      fontSize: "20px",
      fontWeight: "700",
      marginBottom: "6px",
      color: "#ffffff",
    },
    enterpriseCardDesc: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.5)",
      lineHeight: "1.6",
    },
    tagRow: {
      display: "flex",
      flexWrap: "wrap" as const,
      gap: "8px",
    },
    tag: {
      backgroundColor: "rgba(200, 169, 110, 0.08)",
      border: "1px solid rgba(200, 169, 110, 0.2)",
      borderRadius: "8px",
      padding: "6px 14px",
      fontSize: "12px",
      color: "#c8a96e",
      fontWeight: "500",
    },
    guaranteeSection: {
      padding: "80px 24px",
    },
    guaranteeBox: {
      background: "linear-gradient(135deg, rgba(200,169,110,0.06) 0%, rgba(200,169,110,0.02) 100%)",
      border: "1px solid rgba(200, 169, 110, 0.25)",
      borderRadius: "24px",
      padding: "60px 40px",
      textAlign: "center" as const,
      maxWidth: "800px",
      margin: "0 auto",
      position: "relative" as const,
      overflow: "hidden",
    },
    guaranteeGlow: {
      position: "absolute" as const,
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: "400px",
      height: "400px",
      background: "radial-gradient(circle, rgba(200,169,110,0.05) 0%, transparent 70%)",
      pointerEvents: "none" as const,
    },
    guaranteeBadge: {
      width: "90px",
      height: "90px",
      borderRadius: "50%",
      background: "linear-gradient(135deg, rgba(200,169,110,0.2), rgba(200,169,110,0.05))",
      border: "2px solid rgba(200,169,110,0.4)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "36px",
      margin: "0 auto 28px",
    },
    guaranteeTitle: {
      fontSize: "36px",
      fontWeight: "800",
      marginBottom: "16px",
      color: "#ffffff",
    },
    guaranteeText: {
      fontSize: "16px",
      color: "rgba(255,255,255,0.6)",
      lineHeight: "1.8",
      maxWidth: "600px",
      margin: "0 auto 32px",
    },
    guaranteeItems: {
      display: "flex",
      justifyContent: "center",
      flexWrap: "wrap" as const,
      gap: "24px",
      marginTop: "32px",
    },
    guaranteeItem: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontSize: "14px",
      color: "rgba(255,255,255,0.7)",
    },
    guaranteeItemIcon: {
      color: "#c8a96e",
      fontSize: "16px",
    },
    certSection: {
      padding: "80px 24px",
      borderTop: "1px solid rgba(200,169,110,0.08)",
    },
    certBox: {
      display: "flex",
      gap: "40px",
      alignItems: "center",
      flexWrap: "wrap" as const,
    },
    certLeft: {
      flex: "1",
      minWidth: "280px",
    },
    certRight: {
      flex: "1",
      minWidth: "280px",
    },
    certCard: {
      background: "linear-gradient(135deg, rgba(200,169,110,0.1) 0%, rgba(200,169,110,0.03) 100%)",
      border: "1px solid rgba(200,169,110,0.3)",
      borderRadius: "20px",
      padding: "36px",
      textAlign: "center" as const,
    },
    certLogo: {
      fontSize: "48px",
      marginBottom: "16px",
    },
    certName: {
      fontSize: "20px",
      fontWeight: "700",
      color: "#c8a96e",
      marginBottom: "8px",
    },
    certDesc: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.5)",
      lineHeight: "1.6",
    },
    certBadgeRow: {
      display: "flex",
      gap: "12px",
      marginTop: "20px",
      justifyContent: "center",
      flexWrap: "wrap" as const,
    },
    certBadge: {
      backgroundColor: "rgba(200,169,110,0.08)",
      border: "1px solid rgba(200,169,110,0.2)",
      borderRadius: "8px",
      padding: "6px 14px",
      fontSize: "11px",
      color: "#c8a96e",
      fontWeight: "600",
      textTransform: "uppercase" as const,
      letterSpacing: "0.5px",
    },
    stepList: {
      display: "flex",
      flexDirection: "column" as const,
      gap: "20px",
    },
    step: {
      display: "flex",
      gap: "16px",
      alignItems: "flex-start",
    },
    stepNum: {
      width: "36px",
      height: "36px",
      borderRadius: "10px",
      backgroundColor: "rgba(200,169,110,0