export default function TarifsPage() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      backgroundColor: '#050508',
      minHeight: '100vh',
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      color: '#e8e0d0',
      padding: '0',
      margin: '0',
    },
    header: {
      textAlign: 'center',
      padding: '80px 20px 60px',
      background: 'linear-gradient(180deg, #0d0d15 0%, #050508 100%)',
      borderBottom: '1px solid rgba(200,169,110,0.15)',
    },
    badge: {
      display: 'inline-block',
      backgroundColor: 'rgba(200,169,110,0.1)',
      border: '1px solid rgba(200,169,110,0.4)',
      color: '#c8a96e',
      fontSize: '12px',
      fontWeight: '600',
      letterSpacing: '3px',
      textTransform: 'uppercase' as const,
      padding: '6px 20px',
      borderRadius: '20px',
      marginBottom: '24px',
    },
    mainTitle: {
      fontSize: 'clamp(32px, 5vw, 64px)',
      fontWeight: '800',
      margin: '0 0 16px',
      lineHeight: '1.1',
      background: 'linear-gradient(135deg, #ffffff 0%, #c8a96e 50%, #e8d5a3 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      backgroundClip: 'text',
    },
    subtitle: {
      fontSize: '18px',
      color: 'rgba(232,224,208,0.6)',
      margin: '0 auto',
      maxWidth: '600px',
      lineHeight: '1.6',
    },
    section: {
      padding: '60px 20px',
      maxWidth: '1200px',
      margin: '0 auto',
    },
    sectionTitle: {
      textAlign: 'center' as const,
      fontSize: '28px',
      fontWeight: '700',
      color: '#c8a96e',
      marginBottom: '12px',
      letterSpacing: '0.5px',
    },
    sectionSubtitle: {
      textAlign: 'center' as const,
      fontSize: '15px',
      color: 'rgba(232,224,208,0.5)',
      marginBottom: '48px',
      letterSpacing: '1px',
    },
    divider: {
      width: '60px',
      height: '2px',
      background: 'linear-gradient(90deg, transparent, #c8a96e, transparent)',
      margin: '12px auto 48px',
      border: 'none',
    },
    tiersGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
      gap: '24px',
      marginBottom: '0',
    },
    tierCard: {
      backgroundColor: '#0a0a12',
      border: '1px solid rgba(200,169,110,0.15)',
      borderRadius: '20px',
      padding: '40px 32px',
      position: 'relative' as const,
      overflow: 'hidden' as const,
      transition: 'transform 0.2s ease',
    },
    tierCardFeatured: {
      backgroundColor: '#0d0d18',
      border: '1px solid rgba(200,169,110,0.5)',
      borderRadius: '20px',
      padding: '40px 32px',
      position: 'relative' as const,
      overflow: 'hidden' as const,
      boxShadow: '0 0 40px rgba(200,169,110,0.08)',
    },
    featuredRibbon: {
      position: 'absolute' as const,
      top: '20px',
      right: '-30px',
      backgroundColor: '#c8a96e',
      color: '#050508',
      fontSize: '11px',
      fontWeight: '800',
      letterSpacing: '2px',
      textTransform: 'uppercase' as const,
      padding: '6px 50px',
      transform: 'rotate(45deg)',
    },
    tierIcon: {
      fontSize: '40px',
      marginBottom: '20px',
      display: 'block',
    },
    tierName: {
      fontSize: '22px',
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: '8px',
    },
    tierDescription: {
      fontSize: '14px',
      color: 'rgba(232,224,208,0.5)',
      marginBottom: '28px',
      lineHeight: '1.6',
    },
    tierFeatureList: {
      listStyle: 'none',
      padding: '0',
      margin: '0',
    },
    tierFeatureItem: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '10px',
      fontSize: '14px',
      color: 'rgba(232,224,208,0.75)',
      marginBottom: '12px',
      lineHeight: '1.5',
    },
    featureCheck: {
      color: '#c8a96e',
      fontSize: '16px',
      flexShrink: 0,
      marginTop: '1px',
    },
    sessionsSection: {
      padding: '0 20px 60px',
    },
    sessionsContainer: {
      maxWidth: '1200px',
      margin: '0 auto',
    },
    sessionsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
      gap: '24px',
    },
    sessionCard: {
      backgroundColor: '#0a0a12',
      border: '1px solid rgba(200,169,110,0.12)',
      borderRadius: '20px',
      padding: '36px',
      overflow: 'hidden' as const,
    },
    sessionHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '14px',
      marginBottom: '32px',
    },
    sessionIcon: {
      width: '48px',
      height: '48px',
      backgroundColor: 'rgba(200,169,110,0.1)',
      border: '1px solid rgba(200,169,110,0.3)',
      borderRadius: '12px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '22px',
    },
    sessionTypeTitle: {
      fontSize: '20px',
      fontWeight: '700',
      color: '#ffffff',
      margin: '0 0 4px',
    },
    sessionTypeSubtitle: {
      fontSize: '13px',
      color: 'rgba(200,169,110,0.7)',
      margin: '0',
    },
    sessionLevels: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '12px',
    },
    sessionLevel: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: 'rgba(255,255,255,0.02)',
      border: '1px solid rgba(200,169,110,0.08)',
      borderRadius: '12px',
      padding: '16px 20px',
    },
    sessionLevelLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    levelDot: {
      width: '8px',
      height: '8px',
      borderRadius: '50%',
      flexShrink: 0,
    },
    sessionLevelName: {
      fontSize: '15px',
      fontWeight: '600',
      color: '#e8e0d0',
      marginBottom: '2px',
    },
    sessionLevelDesc: {
      fontSize: '12px',
      color: 'rgba(232,224,208,0.4)',
    },
    sessionPrice: {
      textAlign: 'right' as const,
    },
    priceAmount: {
      fontSize: '22px',
      fontWeight: '800',
      color: '#c8a96e',
      display: 'block',
    },
    priceUnit: {
      fontSize: '11px',
      color: 'rgba(200,169,110,0.5)',
      letterSpacing: '1px',
    },
    packsSection: {
      padding: '0 20px 60px',
    },
    packsContainer: {
      maxWidth: '1200px',
      margin: '0 auto',
    },
    packsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: '16px',
    },
    packCard: {
      backgroundColor: '#0a0a12',
      border: '1px solid rgba(200,169,110,0.12)',
      borderRadius: '16px',
      padding: '28px 20px',
      textAlign: 'center' as const,
      position: 'relative' as const,
    },
    packCardPopular: {
      backgroundColor: '#0d0d18',
      border: '1px solid rgba(200,169,110,0.45)',
      borderRadius: '16px',
      padding: '28px 20px',
      textAlign: 'center' as const,
      position: 'relative' as const,
      boxShadow: '0 4px 30px rgba(200,169,110,0.06)',
    },
    packBadge: {
      position: 'absolute' as const,
      top: '-10px',
      left: '50%',
      transform: 'translateX(-50%)',
      backgroundColor: '#c8a96e',
      color: '#050508',
      fontSize: '10px',
      fontWeight: '800',
      letterSpacing: '1.5px',
      textTransform: 'uppercase' as const,
      padding: '3px 12px',
      borderRadius: '10px',
      whiteSpace: 'nowrap' as const,
    },
    packName: {
      fontSize: '15px',
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: '6px',
    },
    packDesc: {
      fontSize: '12px',
      color: 'rgba(232,224,208,0.4)',
      marginBottom: '16px',
      lineHeight: '1.5',
    },
    packPrice: {
      fontSize: '28px',
      fontWeight: '800',
      color: '#c8a96e',
      display: 'block',
      marginBottom: '4px',
    },
    packAccess: {
      fontSize: '11px',
      color: 'rgba(232,224,208,0.35)',
      letterSpacing: '0.5px',
    },
    guaranteeSection: {
      padding: '0 20px 60px',
    },
    guaranteeContainer: {
      maxWidth: '1200px',
      margin: '0 auto',
    },
    guaranteeGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
      gap: '24px',
    },
    guaranteeCard: {
      backgroundColor: '#0a0a12',
      border: '1px solid rgba(200,169,110,0.15)',
      borderRadius: '20px',
      padding: '36px',
      display: 'flex',
      gap: '20px',
      alignItems: 'flex-start',
    },
    guaranteeIcon: {
      width: '56px',
      height: '56px',
      backgroundColor: 'rgba(200,169,110,0.1)',
      border: '1px solid rgba(200,169,110,0.3)',
      borderRadius: '14px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '26px',
      flexShrink: 0,
    },
    guaranteeTitle: {
      fontSize: '18px',
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: '8px',
    },
    guaranteeText: {
      fontSize: '14px',
      color: 'rgba(232,224,208,0.55)',
      lineHeight: '1.7',
    },
    ctaSection: {
      padding: '60px 20px 100px',
      textAlign: 'center' as const,
      background: 'linear-gradient(180deg, #050508 0%, #0a0a12 50%, #050508 100%)',
    },
    ctaBox: {
      maxWidth: '700px',
      margin: '0 auto',
      backgroundColor: '#0a0a12',
      border: '1px solid rgba(200,169,110,0.2)',
      borderRadius: '24px',
      padding: '60px 40px',
      position: 'relative' as const,
      overflow: 'hidden' as const,
    },
    ctaGlow: {
      position: 'absolute' as const,
      top: '-100px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '300px',
      height: '200px',
      background: 'radial-gradient(ellipse, rgba(200,169,110,0.08) 0%, transparent 70%)',
      pointerEvents: 'none' as const,
    },
    ctaTitle: {
      fontSize: '32px',
      fontWeight: '800',
      color: '#ffffff',
      marginBottom: '16px',
      lineHeight: '1.2',
    },
    ctaText: {
      fontSize: '16px',
      color: 'rgba(232,224,208,0.55)',
      marginBottom: '40px',
      lineHeight: '1.6',
    },
    ctaButtons: {
      display: 'flex',
      gap: '16px',
      justifyContent: 'center',
      flexWrap: 'wrap' as const,
    },
    btnPrimary: {
      backgroundColor: '#c8a96e',
      color: '#050508',
      border: 'none',
      borderRadius: '12px',
      padding: '16px 36px',
      fontSize: '15px',
      fontWeight: '800',
      cursor: 'pointer',
      letterSpacing: '0.5px',
    },
    btnSecondary: {
      backgroundColor: 'transparent',
      color: '#c8a96e',
      border: '1px solid rgba(200,169,110,0.4)',
      borderRadius: '12px',
      padding: '16px 36px',
      fontSize: '15px',
      fontWeight: '700',
      cursor: 'pointer',
      letterSpacing: '0.5px',
    },
    footer: {
      borderTop: '1px solid rgba(200,169,110,0.08)',
      padding: '30px 20px',
      textAlign: 'center' as const,
      fontSize: '13px',
}}}