export default function StarterPackPage() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      minHeight: "100vh",
      backgroundColor: "#050508",
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      color: "#ffffff",
      padding: "0",
      margin: "0",
    },
    header: {
      borderBottom: "1px solid rgba(200, 169, 110, 0.2)",
      padding: "20px 40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "rgba(200, 169, 110, 0.03)",
    },
    logo: {
      fontSize: "22px",
      fontWeight: "700",
      color: "#c8a96e",
      letterSpacing: "0.5px",
    },
    logoBadge: {
      fontSize: "11px",
      color: "rgba(200, 169, 110, 0.7)",
      fontWeight: "400",
      display: "block",
      letterSpacing: "2px",
      textTransform: "uppercase" as const,
      marginTop: "2px",
    },
    statusBadge: {
      backgroundColor: "rgba(34, 197, 94, 0.12)",
      border: "1px solid rgba(34, 197, 94, 0.35)",
      color: "#4ade80",
      padding: "6px 14px",
      borderRadius: "20px",
      fontSize: "12px",
      fontWeight: "600",
      letterSpacing: "0.5px",
    },
    heroSection: {
      textAlign: "center" as const,
      padding: "70px 40px 50px",
      maxWidth: "900px",
      margin: "0 auto",
    },
    welcomeBadge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      backgroundColor: "rgba(200, 169, 110, 0.1)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      borderRadius: "30px",
      padding: "8px 20px",
      fontSize: "13px",
      color: "#c8a96e",
      marginBottom: "30px",
      letterSpacing: "0.5px",
    },
    heroTitle: {
      fontSize: "48px",
      fontWeight: "800",
      lineHeight: "1.15",
      marginBottom: "20px",
      background: "linear-gradient(135deg, #ffffff 0%, #c8a96e 50%, #ffffff 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
    },
    heroSubtitle: {
      fontSize: "18px",
      color: "rgba(255,255,255,0.6)",
      lineHeight: "1.7",
      maxWidth: "600px",
      margin: "0 auto 40px",
    },
    dividerLine: {
      width: "60px",
      height: "2px",
      background: "linear-gradient(90deg, transparent, #c8a96e, transparent)",
      margin: "0 auto 60px",
    },
    mainContent: {
      maxWidth: "1100px",
      margin: "0 auto",
      padding: "0 40px 80px",
    },
    sectionTitle: {
      fontSize: "13px",
      color: "#c8a96e",
      fontWeight: "700",
      letterSpacing: "3px",
      textTransform: "uppercase" as const,
      marginBottom: "24px",
    },
    accessGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(2, 1fr)",
      gap: "16px",
      marginBottom: "60px",
    },
    accessCard: {
      backgroundColor: "rgba(255,255,255,0.03)",
      border: "1px solid rgba(200, 169, 110, 0.15)",
      borderRadius: "16px",
      padding: "28px",
      position: "relative" as const,
      overflow: "hidden" as const,
      transition: "border-color 0.2s",
    },
    accessCardAccent: {
      position: "absolute" as const,
      top: "0",
      left: "0",
      right: "0",
      height: "2px",
      background: "linear-gradient(90deg, transparent, #c8a96e, transparent)",
    },
    accessIcon: {
      fontSize: "36px",
      marginBottom: "16px",
      display: "block",
    },
    accessCardTitle: {
      fontSize: "17px",
      fontWeight: "700",
      color: "#ffffff",
      marginBottom: "8px",
    },
    accessCardDesc: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.5)",
      lineHeight: "1.6",
    },
    accessCardBadge: {
      display: "inline-block",
      backgroundColor: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.25)",
      borderRadius: "8px",
      padding: "4px 10px",
      fontSize: "11px",
      color: "#c8a96e",
      fontWeight: "600",
      marginTop: "14px",
      letterSpacing: "0.5px",
    },
    promptsCard: {
      backgroundColor: "rgba(200, 169, 110, 0.06)",
      border: "1px solid rgba(200, 169, 110, 0.25)",
      borderRadius: "16px",
      padding: "28px",
      position: "relative" as const,
      overflow: "hidden" as const,
    },
    promptsNumber: {
      fontSize: "64px",
      fontWeight: "900",
      color: "#c8a96e",
      lineHeight: "1",
      marginBottom: "4px",
    },
    upsellSection: {
      background: "linear-gradient(135deg, rgba(200, 169, 110, 0.08) 0%, rgba(200, 169, 110, 0.03) 100%)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      borderRadius: "20px",
      padding: "50px 40px",
      textAlign: "center" as const,
      position: "relative" as const,
      overflow: "hidden" as const,
      marginBottom: "40px",
    },
    upsellGlow: {
      position: "absolute" as const,
      top: "-50px",
      left: "50%",
      transform: "translateX(-50%)",
      width: "300px",
      height: "200px",
      background: "radial-gradient(ellipse, rgba(200, 169, 110, 0.15) 0%, transparent 70%)",
      pointerEvents: "none" as const,
    },
    upsellBadge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "6px",
      backgroundColor: "rgba(239, 68, 68, 0.15)",
      border: "1px solid rgba(239, 68, 68, 0.35)",
      borderRadius: "20px",
      padding: "6px 16px",
      fontSize: "12px",
      color: "#f87171",
      fontWeight: "700",
      marginBottom: "24px",
      letterSpacing: "0.5px",
    },
    upsellTitle: {
      fontSize: "32px",
      fontWeight: "800",
      color: "#ffffff",
      marginBottom: "12px",
      lineHeight: "1.2",
    },
    upsellTitleGold: {
      color: "#c8a96e",
    },
    upsellSubtitle: {
      fontSize: "16px",
      color: "rgba(255,255,255,0.55)",
      marginBottom: "32px",
      lineHeight: "1.6",
      maxWidth: "500px",
      margin: "0 auto 32px",
    },
    priceRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "16px",
      marginBottom: "32px",
    },
    priceOriginal: {
      fontSize: "22px",
      color: "rgba(255,255,255,0.3)",
      textDecoration: "line-through",
    },
    priceNew: {
      fontSize: "42px",
      fontWeight: "900",
      color: "#c8a96e",
    },
    priceSave: {
      backgroundColor: "rgba(200, 169, 110, 0.15)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      borderRadius: "10px",
      padding: "6px 14px",
      fontSize: "13px",
      color: "#c8a96e",
      fontWeight: "700",
    },
    upsellFeatures: {
      display: "flex",
      justifyContent: "center",
      gap: "24px",
      flexWrap: "wrap" as const,
      marginBottom: "36px",
    },
    upsellFeatureItem: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontSize: "14px",
      color: "rgba(255,255,255,0.7)",
    },
    featureCheck: {
      color: "#c8a96e",
      fontWeight: "700",
    },
    ctaButton: {
      display: "inline-flex",
      alignItems: "center",
      gap: "10px",
      background: "linear-gradient(135deg, #c8a96e 0%, #a8893e 100%)",
      color: "#050508",
      border: "none",
      borderRadius: "12px",
      padding: "16px 36px",
      fontSize: "16px",
      fontWeight: "800",
      cursor: "pointer",
      letterSpacing: "0.3px",
      boxShadow: "0 8px 32px rgba(200, 169, 110, 0.3)",
    },
    secondaryButton: {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      backgroundColor: "transparent",
      color: "rgba(255,255,255,0.5)",
      border: "1px solid rgba(255,255,255,0.1)",
      borderRadius: "12px",
      padding: "14px 28px",
      fontSize: "14px",
      fontWeight: "600",
      cursor: "pointer",
      marginLeft: "16px",
    },
    quickStartSection: {
      marginBottom: "60px",
    },
    stepsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "16px",
    },
    stepCard: {
      backgroundColor: "rgba(255,255,255,0.02)",
      border: "1px solid rgba(255,255,255,0.07)",
      borderRadius: "14px",
      padding: "24px",
    },
    stepNumber: {
      width: "32px",
      height: "32px",
      borderRadius: "50%",
      backgroundColor: "rgba(200, 169, 110, 0.15)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "13px",
      fontWeight: "700",
      color: "#c8a96e",
      marginBottom: "16px",
    },
    stepTitle: {
      fontSize: "15px",
      fontWeight: "700",
      color: "#ffffff",
      marginBottom: "8px",
    },
    stepDesc: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.45)",
      lineHeight: "1.6",
    },
    footer: {
      borderTop: "1px solid rgba(200, 169, 110, 0.1)",
      padding: "30px 40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      maxWidth: "1100px",
      margin: "0 auto",
    },
    footerText: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.3)",
    },
    footerLinks: {
      display: "flex",
      gap: "24px",
    },
    footerLink: {
      fontSize: "13px",
      color: "rgba(200, 169, 110, 0.5)",
      textDecoration: "none",
      cursor: "pointer",
    },
  };

  const accessItems = [
    {
      icon: "🤖",
      title: "100 Prompts Claude par Métier",
      desc: "Bibliothèque complète de prompts optimisés, classés par secteur d'activité et cas d'usage professionnel.",
      badge: "Accès immédiat",
    },
    {
      icon: "📄",
      title: "Guide Démarrage PDF",
      desc: "Manuel de 45 pages pour maîtriser Claude rapidement. Méthodes, frameworks et exemples concrets.",
      badge: "Téléchargement",
    },
    {
      icon: "🎓",
      title: "Module 1 — Formation F128",
      desc: "Premier module de la formation Expert Claude. Introduction aux fondations de l'IA conversationnelle.",
      badge: "Module débloqué",
    },
    {
      icon: "💬",
      title: "Communauté Discord",
      desc: "Accès au serveur privé AcadémIA. Échanges entre membres, Q&A hebdomadaires et ressources exclusives.",
      badge: "Invitation envoyée",
    },
  ];

  const steps = [
    {
      num: "01",
      title: "Téléchargez le Guide PDF",
      desc: "Commencez par le guide démarrage pour poser les bases solides avant d'utiliser les prompts.",
    },
    {
      num: "02",
      title: "Explorez vos 100 Prompts",
      desc: "Filtrez par métier et testez directement sur Claude.ai. Chaque prompt inclut les variantes.",
    },
    {
      num: "03",
      title: "Rejoignez le Discord",
      desc: "Présentez-vous dans #introductions et accédez aux ressources communautaires exclusives.",
    },
  ];

  const upsellFeatures = [
    "12 modules complets",
    "500+ prompts avancés",
    "Projets pratiques",
    "Certification F128",
    "Support prioritaire",
  ];

  return (
    <div style={styles.page}>
      <header style={styles.header}>
        <div>
          <div style={styles.logo}>AcadémIA Pro</div>
          <span style={styles.logoBadge}>Starter Pack IA</span>
        </div>
        <div style={styles.