export default function MesSéances() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      minHeight: "100vh",
      backgroundColor: "#050508",
      color: "#e8e0d0",
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      padding: "0",
      margin: "0",
    },
    header: {
      background: "linear-gradient(135deg, #0a0a0f 0%, #12100e 100%)",
      borderBottom: "1px solid rgba(200, 169, 110, 0.2)",
      padding: "24px 40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    logo: {
      fontSize: "22px",
      fontWeight: "700",
      color: "#c8a96e",
      letterSpacing: "0.5px",
    },
    logoSub: {
      fontSize: "11px",
      color: "rgba(200, 169, 110, 0.6)",
      letterSpacing: "2px",
      textTransform: "uppercase" as const,
      marginTop: "2px",
    },
    headerRight: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
    },
    avatar: {
      width: "40px",
      height: "40px",
      borderRadius: "50%",
      background: "linear-gradient(135deg, #c8a96e, #9a7a3e)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "16px",
      fontWeight: "700",
      color: "#050508",
      cursor: "pointer",
    },
    main: {
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "40px 40px",
    },
    pageTitle: {
      fontSize: "32px",
      fontWeight: "700",
      color: "#ffffff",
      marginBottom: "6px",
    },
    pageSubtitle: {
      fontSize: "15px",
      color: "rgba(232, 224, 208, 0.5)",
      marginBottom: "40px",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "24px",
      marginBottom: "24px",
    },
    gridFull: {
      display: "grid",
      gridTemplateColumns: "1fr",
      gap: "24px",
      marginBottom: "24px",
    },
    card: {
      background: "linear-gradient(145deg, #0d0d12 0%, #0a0a0e 100%)",
      border: "1px solid rgba(200, 169, 110, 0.15)",
      borderRadius: "16px",
      padding: "28px",
    },
    cardGold: {
      background: "linear-gradient(145deg, #12100a 0%, #0e0c08 100%)",
      border: "1px solid rgba(200, 169, 110, 0.35)",
      borderRadius: "16px",
      padding: "28px",
    },
    cardHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: "22px",
    },
    cardTitle: {
      fontSize: "16px",
      fontWeight: "600",
      color: "#c8a96e",
      letterSpacing: "0.3px",
    },
    cardIcon: {
      fontSize: "20px",
      opacity: 0.7,
    },
    sessionItem: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "14px 16px",
      background: "rgba(200, 169, 110, 0.04)",
      border: "1px solid rgba(200, 169, 110, 0.1)",
      borderRadius: "10px",
      marginBottom: "10px",
    },
    sessionLeft: {
      display: "flex",
      alignItems: "center",
      gap: "14px",
    },
    sessionIconBox: {
      width: "42px",
      height: "42px",
      borderRadius: "10px",
      background: "rgba(200, 169, 110, 0.1)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "18px",
    },
    sessionTitle: {
      fontSize: "14px",
      fontWeight: "600",
      color: "#ffffff",
      marginBottom: "3px",
    },
    sessionMeta: {
      fontSize: "12px",
      color: "rgba(232, 224, 208, 0.45)",
    },
    badgeLive: {
      display: "inline-flex",
      alignItems: "center",
      gap: "5px",
      background: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.3)",
      borderRadius: "20px",
      padding: "3px 10px",
      fontSize: "11px",
      color: "#c8a96e",
      fontWeight: "600",
      marginBottom: "4px",
    },
    dot: {
      width: "6px",
      height: "6px",
      borderRadius: "50%",
      background: "#c8a96e",
    },
    btnPrimary: {
      background: "linear-gradient(135deg, #c8a96e 0%, #a8843e 100%)",
      color: "#050508",
      border: "none",
      borderRadius: "8px",
      padding: "8px 16px",
      fontSize: "12px",
      fontWeight: "700",
      cursor: "pointer",
      letterSpacing: "0.3px",
      whiteSpace: "nowrap" as const,
    },
    btnSecondary: {
      background: "transparent",
      color: "#c8a96e",
      border: "1px solid rgba(200, 169, 110, 0.4)",
      borderRadius: "8px",
      padding: "8px 16px",
      fontSize: "12px",
      fontWeight: "600",
      cursor: "pointer",
      letterSpacing: "0.3px",
      whiteSpace: "nowrap" as const,
    },
    btnGhost: {
      background: "rgba(200, 169, 110, 0.07)",
      color: "rgba(232, 224, 208, 0.6)",
      border: "1px solid rgba(200, 169, 110, 0.1)",
      borderRadius: "8px",
      padding: "8px 16px",
      fontSize: "12px",
      fontWeight: "600",
      cursor: "pointer",
      whiteSpace: "nowrap" as const,
    },
    divider: {
      height: "1px",
      background: "rgba(200, 169, 110, 0.1)",
      margin: "16px 0",
    },
    subscriptionRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: "12px",
    },
    subscriptionLabel: {
      fontSize: "13px",
      color: "rgba(232, 224, 208, 0.5)",
    },
    subscriptionValue: {
      fontSize: "13px",
      color: "#ffffff",
      fontWeight: "600",
    },
    planBadge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "6px",
      background: "linear-gradient(135deg, rgba(200,169,110,0.15), rgba(200,169,110,0.05))",
      border: "1px solid rgba(200, 169, 110, 0.4)",
      borderRadius: "8px",
      padding: "4px 12px",
      fontSize: "12px",
      color: "#c8a96e",
      fontWeight: "700",
      letterSpacing: "0.5px",
    },
    specialtyGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "12px",
      marginBottom: "20px",
    },
    specialtyCard: {
      background: "rgba(200, 169, 110, 0.04)",
      border: "1px solid rgba(200, 169, 110, 0.12)",
      borderRadius: "10px",
      padding: "14px 12px",
      cursor: "pointer",
      textAlign: "center" as const,
      transition: "all 0.2s",
    },
    specialtyCardActive: {
      background: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.45)",
      borderRadius: "10px",
      padding: "14px 12px",
      cursor: "pointer",
      textAlign: "center" as const,
    },
    specialtyIcon: {
      fontSize: "22px",
      marginBottom: "6px",
    },
    specialtyName: {
      fontSize: "11px",
      color: "rgba(232, 224, 208, 0.7)",
      fontWeight: "600",
      lineHeight: "1.3",
    },
    modeRow: {
      display: "flex",
      gap: "12px",
      marginBottom: "20px",
    },
    modeBtn: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      padding: "12px",
      background: "rgba(200, 169, 110, 0.04)",
      border: "1px solid rgba(200, 169, 110, 0.12)",
      borderRadius: "10px",
      cursor: "pointer",
      fontSize: "13px",
      color: "rgba(232, 224, 208, 0.6)",
      fontWeight: "600",
    },
    modeBtnActive: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      padding: "12px",
      background: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.45)",
      borderRadius: "10px",
      cursor: "pointer",
      fontSize: "13px",
      color: "#c8a96e",
      fontWeight: "700",
    },
    bookingBtn: {
      width: "100%",
      background: "linear-gradient(135deg, #c8a96e 0%, #a8843e 100%)",
      color: "#050508",
      border: "none",
      borderRadius: "10px",
      padding: "14px",
      fontSize: "14px",
      fontWeight: "700",
      cursor: "pointer",
      letterSpacing: "0.5px",
    },
    historyBadge: {
      display: "inline-block",
      padding: "2px 8px",
      borderRadius: "6px",
      fontSize: "10px",
      fontWeight: "700",
      letterSpacing: "0.5px",
    },
    statsRow: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "12px",
      marginBottom: "22px",
    },
    statBox: {
      background: "rgba(200, 169, 110, 0.05)",
      border: "1px solid rgba(200, 169, 110, 0.1)",
      borderRadius: "10px",
      padding: "12px",
      textAlign: "center" as const,
    },
    statNumber: {
      fontSize: "22px",
      fontWeight: "700",
      color: "#c8a96e",
      lineHeight: "1",
      marginBottom: "4px",
    },
    statLabel: {
      fontSize: "10px",
      color: "rgba(232, 224, 208, 0.4)",
      letterSpacing: "0.5px",
      textTransform: "uppercase" as const,
    },
    emptyState: {
      textAlign: "center" as const,
      padding: "30px 20px",
      color: "rgba(232, 224, 208, 0.3)",
      fontSize: "13px",
    },
    navTabs: {
      display: "flex",
      gap: "4px",
      background: "rgba(200, 169, 110, 0.05)",
      border: "1px solid rgba(200, 169, 110, 0.1)",
      borderRadius: "10px",
      padding: "4px",
      marginBottom: "28px",
    },
    navTab: {
      flex: 1,
      padding: "10px 16px",
      background: "transparent",
      border: "none",
      borderRadius: "7px",
      color: "rgba(232, 224, 208, 0.45)",
      fontSize: "13px",
      fontWeight: "600",
      cursor: "pointer",
    },
    navTabActive: {
      flex: 1,
      padding: "10px 16px",
      background: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.25)",
      borderRadius: "7px",
      color: "#c8a96e",
      fontSize: "13px",
      fontWeight: "700",
      cursor: "pointer",
    },
  };

  const upcomingSessions = [
    {
      id: 1,
      title: "Mathématiques avancées",
      tutor: "Dr. Isabelle Moreau",
      date: "Aujourd'hui",
      time: "18h00 – 19h30",
      mode: "Visio",
      icon: "📐",
      isToday: true,
    },
    {
      id: 2,
      title: "Physique quantique",
      tutor: "Prof. Antoine Leclerc",
      date: "Demain",
      time: "14h00 – 15h30",
      mode: "Visio",
      icon: "⚛️",
      isToday: false,
    },
    {
      id: 3,
      title: "Littérature française",
      tutor: "Mme. Claire Dupont",
      date: "Ven. 17 jan.",
      time: "10h00 – 11h00",
      mode: "Audio",
      icon: "📖",
      isToday: false,
    },
  ];

  const pastSessions = [
    {
      id: 1,
      title: "Chimie organique",
      tutor: "Dr. Paul Bernard",
      date: "Lun. 13 jan.",
      duration: "90 min",
      score: "Excellent",
      icon: "🧪",
      scoreColor: "#4ade80",
    },
    {
      id: 2,
      title: "Algèbre linéaire",
      tutor: "Prof. Isabelle Moreau",