export default function CataloguePage() {
  const formations = [
    { code: "IA-001", titre: "Introduction à l'Intelligence Artificielle", domaine: "IA", prix: 297, duree: "8h" },
    { code: "IA-002", titre: "Machine Learning avec Python", domaine: "IA", prix: 397, duree: "12h" },
    { code: "IA-003", titre: "Deep Learning et Réseaux de Neurones", domaine: "IA", prix: 447, duree: "15h" },
    { code: "IA-004", titre: "ChatGPT et LLMs pour Professionnels", domaine: "IA", prix: 197, duree: "6h" },
    { code: "IA-005", titre: "Computer Vision avec TensorFlow", domaine: "IA", prix: 497, duree: "18h" },
    { code: "IA-006", titre: "NLP et Traitement du Langage Naturel", domaine: "IA", prix: 447, duree: "14h" },
    { code: "IA-007", titre: "IA Générative et Création de Contenu", domaine: "IA", prix: 297, duree: "9h" },
    { code: "IA-008", titre: "Prompt Engineering Avancé", domaine: "IA", prix: 147, duree: "4h" },
    { code: "IA-009", titre: "AutoML et No-Code IA", domaine: "IA", prix: 247, duree: "7h" },
    { code: "IA-010", titre: "IA pour la Finance et Prédiction", domaine: "IA", prix: 547, duree: "16h" },
    { code: "BE-001", titre: "Méditation de Pleine Conscience", domaine: "Bien-etre", prix: 147, duree: "5h" },
    { code: "BE-002", titre: "Gestion du Stress par la Sophrologie", domaine: "Bien-etre", prix: 197, duree: "7h" },
    { code: "BE-003", titre: "Yoga Fondamental pour Débutants", domaine: "Bien-etre", prix: 127, duree: "6h" },
    { code: "BE-004", titre: "Nutrition et Alimentation Saine", domaine: "Bien-etre", prix: 167, duree: "8h" },
    { code: "BE-005", titre: "Psychologie Positive au Quotidien", domaine: "Bien-etre", prix: 197, duree: "9h" },
    { code: "BE-006", titre: "Sommeil et Récupération Optimale", domaine: "Bien-etre", prix: 147, duree: "4h" },
    { code: "BE-007", titre: "Cohérence Cardiaque et Respiration", domaine: "Bien-etre", prix: 97, duree: "3h" },
    { code: "BE-008", titre: "Développement Personnel Intensif", domaine: "Bien-etre", prix: 297, duree: "12h" },
    { code: "BE-009", titre: "Gestion des Émotions et Intelligence Émotionnelle", domaine: "Bien-etre", prix: 247, duree: "10h" },
    { code: "BE-010", titre: "Hypnose Ericksonienne Fondamentaux", domaine: "Bien-etre", prix: 347, duree: "14h" },
    { code: "LG-001", titre: "Anglais Business Niveau B2", domaine: "Langues", prix: 297, duree: "20h" },
    { code: "LG-002", titre: "Espagnol pour Voyageurs", domaine: "Langues", prix: 197, duree: "15h" },
    { code: "LG-003", titre: "Mandarin Débutant Complet", domaine: "Langues", prix: 347, duree: "25h" },
    { code: "LG-004", titre: "Allemand Professionnel", domaine: "Langues", prix: 297, duree: "22h" },
    { code: "LG-005", titre: "Français Langue Étrangère FLE", domaine: "Langues", prix: 247, duree: "18h" },
    { code: "LG-006", titre: "Italien Conversation Rapide", domaine: "Langues", prix: 197, duree: "12h" },
    { code: "LG-007", titre: "Anglais Technique IT", domaine: "Langues", prix: 247, duree: "14h" },
    { code: "LG-008", titre: "Japonais Hiragana et Katakana", domaine: "Langues", prix: 297, duree: "20h" },
    { code: "LG-009", titre: "Portugais Brésilien Débutant", domaine: "Langues", prix: 197, duree: "16h" },
    { code: "LG-010", titre: "Arabe Standard Moderne", domaine: "Langues", prix: 347, duree: "24h" },
    { code: "BU-001", titre: "Création d'Entreprise de A à Z", domaine: "Business", prix: 447, duree: "16h" },
    { code: "BU-002", titre: "Finance d'Entreprise pour Non-Financiers", domaine: "Business", prix: 347, duree: "12h" },
    { code: "BU-003", titre: "Négociation Commerciale Avancée", domaine: "Business", prix: 397, duree: "14h" },
    { code: "BU-004", titre: "Excel pour Business Intelligence", domaine: "Business", prix: 247, duree: "10h" },
    { code: "BU-005", titre: "Stratégie d'Entreprise et Croissance", domaine: "Business", prix: 497, duree: "18h" },
    { code: "BU-006", titre: "Comptabilité et Gestion PME", domaine: "Business", prix: 297, duree: "11h" },
    { code: "BU-007", titre: "Droit des Affaires Essentiel", domaine: "Business", prix: 347, duree: "13h" },
    { code: "BU-008", titre: "Fundraising et Levée de Fonds", domaine: "Business", prix: 447, duree: "15h" },
    { code: "BU-009", titre: "Business Model Canvas Maîtrise", domaine: "Business", prix: 197, duree: "6h" },
    { code: "BU-010", titre: "Gestion de Trésorerie et Cash Flow", domaine: "Business", prix: 297, duree: "9h" },
    { code: "MG-001", titre: "Management d'Équipe Performante", domaine: "Management", prix: 397, duree: "14h" },
    { code: "MG-002", titre: "Leadership Transformationnel", domaine: "Management", prix: 447, duree: "16h" },
    { code: "MG-003", titre: "Gestion de Projet Agile Scrum", domaine: "Management", prix: 347, duree: "12h" },
    { code: "MG-004", titre: "Communication Managériale", domaine: "Management", prix: 297, duree: "10h" },
    { code: "MG-005", titre: "Recrutement et Onboarding", domaine: "Management", prix: 347, duree: "11h" },
    { code: "MG-006", titre: "Conduite du Changement", domaine: "Management", prix: 397, duree: "13h" },
    { code: "MG-007", titre: "Feedback et Évaluation de Performance", domaine: "Management", prix: 247, duree: "7h" },
    { code: "MG-008", titre: "Gestion des Conflits en Entreprise", domaine: "Management", prix: 297, duree: "9h" },
    { code: "MG-009", titre: "Management Hybride et Télétravail", domaine: "Management", prix: 247, duree: "8h" },
    { code: "MG-010", titre: "OKR et Pilotage par Objectifs", domaine: "Management", prix: 347, duree: "11h" },
    { code: "MK-001", titre: "Marketing Digital Complet", domaine: "Marketing", prix: 447, duree: "20h" },
    { code: "MK-002", titre: "SEO et Référencement Naturel", domaine: "Marketing", prix: 297, duree: "12h" },
    { code: "MK-003", titre: "Publicité Facebook et Meta Ads", domaine: "Marketing", prix: 347, duree: "14h" },
    { code: "MK-004", titre: "Email Marketing et Automation", domaine: "Marketing", prix: 247, duree: "9h" },
    { code: "MK-005", titre: "Content Marketing et Storytelling", domaine: "Marketing", prix: 297, duree: "11h" },
    { code: "MK-006", titre: "Google Ads et SEA Avancé", domaine: "Marketing", prix: 347, duree: "13h" },
    { code: "MK-007", titre: "Réseaux Sociaux et Community Management", domaine: "Marketing", prix: 247, duree: "10h" },
    { code: "MK-008", titre: "Inbound Marketing et Lead Generation", domaine: "Marketing", prix: 397, duree: "16h" },
    { code: "MK-009", titre: "Analytics et Data-Driven Marketing", domaine: "Marketing", prix: 347, duree: "13h" },
    { code: "MK-010", titre: "Personal Branding et Influence", domaine: "Marketing", prix: 197, duree: "7h" },
    { code: "IA-011", titre: "IA pour le Marketing Digital", domaine: "IA", prix: 347, duree: "11h" },
    { code: "IA-012", titre: "Automatisation RPA et IA", domaine: "IA", prix: 397, duree: "13h" },
    { code: "IA-013", titre: "Midjourney et DALL-E Maîtrise", domaine: "IA", prix: 197, duree: "6h" },
    { code: "IA-014", titre: "Data Science avec Python", domaine: "IA", prix: 497, duree: "20h" },
    { code: "IA-015", titre: "IA en Cybersécurité", domaine: "IA", prix: 447, duree: "15h" },
    { code: "BE-011", titre: "Mindfulness et Pleine Conscience au Travail", domaine: "Bien-etre", prix: 167, duree: "6h" },
    { code: "BE-012", titre: "Arrêter de Procrastiner", domaine: "Bien-etre", prix: 127, duree: "4h" },
    { code: "BE-013", titre: "Confiance en Soi et Estime", domaine: "Bien-etre", prix: 197, duree: "8h" },
    { code: "BE-014", titre: "Burn-out Prévention et Récupération", domaine: "Bien-etre", prix: 247, duree: "10h" },
    { code: "BE-015", titre: "Sport et Performance Mentale", domaine: "Bien-etre", prix: 167, duree: "6h" },
    { code: "LG-011", titre: "Néerlandais pour Professionnels", domaine: "Langues", prix: 247, duree: "18h" },
    { code: "LG-012", titre: "Russe Débutant Alphabet et Bases", domaine: "Langues", prix: 297, duree: "20h" },
    { code: "LG-013", titre: "Coréen Culture et Communication", domaine: "Langues", prix: 247, duree: "16h" },
    { code: "LG-014", titre: "Anglais TOEIC Préparation", domaine: "Langues", prix: 297, duree: "22h" },
    { code: "LG-015", titre: "Turc Débutant Complet", domaine: "Langues", prix: 197, duree: "14h" },
    { code: "BU-011", titre: "E-commerce et Boutique en Ligne", domaine: "Business", prix: 347, duree: "13h" },
    { code: "BU-012", titre: "Import-Export et Commerce International", domaine: "Business", prix: 397, duree: "15h" },
    { code: "BU-013", titre: "Franchise et Développement Réseau", domaine: "Business", prix: 447, duree: "16h" },
    { code: "BU-014", titre: "Dropshipping et Amazon FBA", domaine: "Business", prix: 297, duree: "11h" },
    { code: "BU-015", titre: "Investissement Immobilier Stratégie", domaine: "Business", prix: 497, duree: "18h" },
    { code: "MG-011", titre: "Cohésion d'Équipe et Team Building", domaine: "Management", prix: 247, duree: "7h" },
    { code: "MG-012", titre: "Intelligence Collective et Innovation", domaine: "Management", prix: 347, duree: "12h" },
    { code: "MG-013", titre: "Management Intergénérationnel", domaine: "Management", prix: 297, duree: "9h" },
    { code: "MG-014", titre: "Gouvernance et Comité de Direction", domaine: "Management", prix: 447, duree: "15h" },
    { code: "MG-015", titre: "Bien-être et QVT en Entreprise", domaine: "Management", prix: 297, duree: "10h" },
    { code: "MK-011", titre: "TikTok Marketing et Vidéo Courte", domaine: "Marketing", prix: 247, duree: "9h" },
    { code: "MK-012", titre: "LinkedIn Strategy B2B", domaine: "Marketing", prix: 297, duree: "11h" },
    { code: "MK-013", titre: "Copywriting et Rédaction Persuasive", domaine: "Marketing", prix: 247, duree: "9h" },
    { code: "MK-014", titre: "Growth Hacking et Acquisition Rapide", domaine: "Marketing", prix: 397, duree: "14h" },
    { code: "MK-015", titre: "Marketing d'Influence et Collaboration", domaine: "Marketing", prix: 297, duree: "10h" },