export default function GarantieAcademiaPro() {
  const styles: Record<string, React.CSSProperties> = {
    page: {
      backgroundColor: "#050508",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      color: "#ffffff",
      overflowX: "hidden",
    },
    container: {
      maxWidth: "900px",
      margin: "0 auto",
      padding: "0 24px",
    },
    header: {
      padding: "60px 0 40px",
      textAlign: "center",
    },
    badgeWrap: {
      display: "flex",
      justifyContent: "center",
      marginBottom: "28px",
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      backgroundColor: "rgba(200, 169, 110, 0.12)",
      border: "1px solid rgba(200, 169, 110, 0.35)",
      borderRadius: "50px",
      padding: "8px 20px",
      fontSize: "13px",
      color: "#c8a96e",
      letterSpacing: "0.06em",
      textTransform: "uppercase" as const,
      fontWeight: 600,
    },
    dot: {
      width: "7px",
      height: "7px",
      backgroundColor: "#c8a96e",
      borderRadius: "50%",
      display: "inline-block",
    },
    heroTitle: {
      fontSize: "clamp(36px, 6vw, 62px)",
      fontWeight: 800,
      lineHeight: 1.1,
      marginBottom: "20px",
      letterSpacing: "-0.02em",
    },
    gradientText: {
      background: "linear-gradient(135deg, #c8a96e 0%, #f0d9a8 50%, #c8a96e 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
    },
    heroSub: {
      fontSize: "18px",
      color: "rgba(255,255,255,0.6)",
      maxWidth: "560px",
      margin: "0 auto",
      lineHeight: 1.7,
    },
    shieldSection: {
      display: "flex",
      justifyContent: "center",
      padding: "48px 0",
    },
    shieldCard: {
      background: "linear-gradient(145deg, rgba(200,169,110,0.08) 0%, rgba(200,169,110,0.03) 100%)",
      border: "1px solid rgba(200,169,110,0.25)",
      borderRadius: "24px",
      padding: "52px 60px",
      textAlign: "center",
      maxWidth: "520px",
      width: "100%",
      position: "relative" as const,
      overflow: "hidden",
    },
    shieldGlow: {
      position: "absolute" as const,
      top: "-60px",
      left: "50%",
      transform: "translateX(-50%)",
      width: "200px",
      height: "200px",
      background: "radial-gradient(circle, rgba(200,169,110,0.15) 0%, transparent 70%)",
      pointerEvents: "none" as const,
    },
    shieldIcon: {
      fontSize: "72px",
      marginBottom: "20px",
      display: "block",
      filter: "drop-shadow(0 0 20px rgba(200,169,110,0.4))",
    },
    shieldTitle: {
      fontSize: "32px",
      fontWeight: 800,
      color: "#c8a96e",
      marginBottom: "8px",
    },
    shieldDays: {
      fontSize: "88px",
      fontWeight: 900,
      color: "#c8a96e",
      lineHeight: 1,
      marginBottom: "4px",
      background: "linear-gradient(180deg, #f0d9a8 0%, #c8a96e 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
    },
    shieldSub: {
      fontSize: "15px",
      color: "rgba(255,255,255,0.5)",
      marginBottom: "24px",
      letterSpacing: "0.08em",
      textTransform: "uppercase" as const,
    },
    shieldDesc: {
      fontSize: "16px",
      color: "rgba(255,255,255,0.7)",
      lineHeight: 1.7,
    },
    divider: {
      height: "1px",
      background: "linear-gradient(90deg, transparent, rgba(200,169,110,0.3), transparent)",
      margin: "48px 0",
    },
    sectionTitle: {
      fontSize: "28px",
      fontWeight: 700,
      marginBottom: "32px",
      textAlign: "center" as const,
    },
    stepsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "20px",
      marginBottom: "60px",
    },
    stepCard: {
      background: "rgba(255,255,255,0.03)",
      border: "1px solid rgba(255,255,255,0.08)",
      borderRadius: "16px",
      padding: "28px 24px",
      textAlign: "center" as const,
      transition: "border-color 0.3s",
    },
    stepNumber: {
      width: "44px",
      height: "44px",
      borderRadius: "50%",
      background: "linear-gradient(135deg, #c8a96e, #f0d9a8)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 800,
      fontSize: "18px",
      color: "#050508",
      margin: "0 auto 16px",
    },
    stepEmoji: {
      fontSize: "32px",
      display: "block",
      marginBottom: "12px",
    },
    stepTitle: {
      fontSize: "16px",
      fontWeight: 700,
      color: "#c8a96e",
      marginBottom: "8px",
    },
    stepDesc: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.55)",
      lineHeight: 1.6,
    },
    coverageSection: {
      marginBottom: "60px",
    },
    coverageGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "16px",
    },
    coverageItem: {
      display: "flex",
      alignItems: "center",
      gap: "14px",
      background: "rgba(255,255,255,0.03)",
      border: "1px solid rgba(255,255,255,0.08)",
      borderRadius: "12px",
      padding: "18px 20px",
    },
    checkIcon: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      background: "rgba(200,169,110,0.15)",
      border: "1px solid rgba(200,169,110,0.4)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "14px",
      flexShrink: 0,
    },
    coverageText: {
      fontSize: "15px",
      color: "rgba(255,255,255,0.8)",
      fontWeight: 500,
    },
    formSection: {
      marginBottom: "80px",
    },
    formCard: {
      background: "rgba(255,255,255,0.03)",
      border: "1px solid rgba(200,169,110,0.2)",
      borderRadius: "20px",
      padding: "40px",
    },
    formTitle: {
      fontSize: "22px",
      fontWeight: 700,
      marginBottom: "8px",
      color: "#ffffff",
    },
    formSubtitle: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.45)",
      marginBottom: "32px",
    },
    formGroup: {
      marginBottom: "20px",
    },
    label: {
      display: "block",
      fontSize: "13px",
      fontWeight: 600,
      color: "rgba(255,255,255,0.6)",
      marginBottom: "8px",
      letterSpacing: "0.04em",
      textTransform: "uppercase" as const,
    },
    required: {
      color: "#c8a96e",
      marginLeft: "3px",
    },
    input: {
      width: "100%",
      backgroundColor: "rgba(255,255,255,0.05)",
      border: "1px solid rgba(255,255,255,0.12)",
      borderRadius: "10px",
      padding: "13px 16px",
      fontSize: "15px",
      color: "#ffffff",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box" as const,
    },
    textarea: {
      width: "100%",
      backgroundColor: "rgba(255,255,255,0.05)",
      border: "1px solid rgba(255,255,255,0.12)",
      borderRadius: "10px",
      padding: "13px 16px",
      fontSize: "15px",
      color: "#ffffff",
      outline: "none",
      resize: "vertical" as const,
      minHeight: "120px",
      fontFamily: "inherit",
      transition: "border-color 0.2s",
      boxSizing: "border-box" as const,
    },
    select: {
      width: "100%",
      backgroundColor: "rgba(10,10,15,0.95)",
      border: "1px solid rgba(255,255,255,0.12)",
      borderRadius: "10px",
      padding: "13px 16px",
      fontSize: "15px",
      color: "#ffffff",
      outline: "none",
      appearance: "none" as const,
      cursor: "pointer",
      boxSizing: "border-box" as const,
    },
    submitBtn: {
      width: "100%",
      padding: "16px",
      background: "linear-gradient(135deg, #c8a96e 0%, #f0d9a8 50%, #c8a96e 100%)",
      backgroundSize: "200% auto",
      border: "none",
      borderRadius: "12px",
      fontSize: "16px",
      fontWeight: 700,
      color: "#050508",
      cursor: "pointer",
      marginTop: "8px",
      letterSpacing: "0.02em",
    },
    notice: {
      display: "flex",
      alignItems: "flex-start",
      gap: "12px",
      background: "rgba(200,169,110,0.07)",
      border: "1px solid rgba(200,169,110,0.2)",
      borderRadius: "12px",
      padding: "16px 18px",
      marginTop: "20px",
    },
    noticeIcon: {
      fontSize: "18px",
      flexShrink: 0,
      marginTop: "1px",
    },
    noticeText: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.55)",
      lineHeight: 1.6,
    },
    faqSection: {
      marginBottom: "80px",
    },
    faqItem: {
      borderBottom: "1px solid rgba(255,255,255,0.07)",
      padding: "22px 0",
    },
    faqQ: {
      fontSize: "16px",
      fontWeight: 600,
      color: "#c8a96e",
      marginBottom: "10px",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    faqA: {
      fontSize: "14px",
      color: "rgba(255,255,255,0.55)",
      lineHeight: 1.7,
      paddingLeft: "24px",
    },
    footer: {
      borderTop: "1px solid rgba(255,255,255,0.07)",
      padding: "40px 0",
      textAlign: "center" as const,
    },
    footerLogo: {
      fontSize: "20px",
      fontWeight: 800,
      color: "#c8a96e",
      marginBottom: "10px",
    },
    footerText: {
      fontSize: "13px",
      color: "rgba(255,255,255,0.3)",
    },
  };

  const coverageItems = [
    "Toutes les formations individuelles",
    "Tous les packs thématiques",
    "Packs multi-formations",
    "Formations avec certificat",
    "Accès à vie garantis",
    "Mises à jour de contenu",
    "Sessions live enregistrées",
    "Ressources téléchargeables",
  ];

  const faqs = [
    {
      q: "Quel est le délai exact pour demander un remboursement ?",
      a: "Vous disposez de 30 jours calendaires à compter de la date d'achat pour soumettre votre demande de remboursement. Passé ce délai, aucune demande ne pourra être traitée.",
    },
    {
      q: "Combien de temps prend le traitement du remboursement ?",
      a: "Une fois votre demande validée, le remboursement est effectué sous 5 à 10 jours ouvrés sur le moyen de paiement utilisé lors de l'achat.",
    },
    {
      q: "Y a-t-il des conditions ou des exclusions ?",
      a: "La garantie s'applique sans condition à toutes les formations et packs AcadémIA Pro. Il n'y a aucun critère d'utilisation minimum ni de justification obligatoire.",
    },
    {
      q: "Puis-je racheter une formation après un remboursement ?",
      a: "Oui, absolument. Un remboursement n'entraîne aucune restriction future. Vous êtes libre de racheter n'importe quelle formation ou pack à tout moment.",
    },
    {
      q: "Comment suivre l'état de ma demande ?",
      a: "Après soumission du formulaire, vous recevrez un email de confirmation avec un numéro de suivi. Notre équipe vous contactera sous 24h ouvrées.",
    },
  ];

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <header style={styles.header}>
          <div style={styles.badgeWrap}>
            <span style={styles.badge}>
              <span style={styles.dot} />
              AcadémIA Pro · Garantie Officielle
            </span>
          </div>
          <h1 style={styles.heroTitle}>
            Votre satisfaction,{" "}
            <span style={styles.gradientText}>notre engagement</span>